{
 "title": "What are the current Globus task summary statistics?",
 "tags": [ "Globus task" ],
 "time": { "from": "2025-05-29T15:30:24.269Z", "to": "2025-06-05T15:30:24.269Z" },
 "templating": {
  "list": [
   {
    "name": "sensors",
    "label": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   {
    "name": "country_scope",
    "label": "Scope",
    "query": "{\"find\":\"terms\", \"field\":\"meta.country_scope\"}"
   },
   {
    "name": "community",
    "label": "Community",
    "query": "{\"find\":\"terms\",\"field\":\"meta.src.community\"}"
   },
   { "name": "confidential", "label": "Display Private Tasks", "query": "Yes : *, No : (-Private)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 21, "x": 2, "y": 0 },
   "options": {
    "content": "<style=\"margin-top: 0px\"><font color=\"#5794f2\"><blockquote><h1><b>Other Globus Task Statistics</b></h1></font>\n<li>This dashboard provides a summary of Task information for science registry tagging, organizations, and countries, as well as volume and counts of Tasks. <p>\n<li>Globus Task datasets have been de-identified. Globus Tasks where the organization is not disclosed are marked \"Private\". </li>\n<li>Private Task data rates and totals are available via the toggle at the top of this dashboard. </li>\n<li>All times are displayed in browser local time.</blockquote>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 6 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Total Task Volume</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Average Task Rate</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:106",
       "field": "start",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:104",
       "field": "meta.src_organization",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:168",
       "field": "meta.src_country_name",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:1381",
       "field": "meta.src_asn",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:1392",
       "field": "meta.dst_asn",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:1403",
       "field": "meta.dst_organization",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:1414",
       "field": "meta.dst_country_name",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      { "field": "values.num_bits", "id": "8", "settings": { "script": "_value/8" }, "type": "sum" },
      {
       "field": "values.bits_per_second",
       "id": "9",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.sensor_id:$sensors AND meta.src_organization:${confidential:raw} AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 8 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Source Organizations</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 8 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Destination Organizations</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 10 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Source ASNs</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 10 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Destination ASNs</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 12 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Source Countries</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 12 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Destination Countries</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND (meta.src_organization:${confidential:raw} AND meta.dst_organization:${confidential:raw}) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.ip_version:4",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 14 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>IPv4 Tasks</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:106",
       "field": "start",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND (meta.src_organization:${confidential:raw} AND meta.dst_organization:${confidential:raw}) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.ip_version:6",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>IPv6 Tasks</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1051",
       "field": "start",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1049",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "meta.sensor_id:$sensors AND ( meta.src_location.data_source:scireg OR meta.dst_location.data_source:scireg ) AND NOT ( meta.src_location.data_source:scireg AND meta.dst_location.data_source:scireg ) AND (meta.src.community:$community OR meta.dst.community:$community)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 16 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Tasks with only one end tagged in Science Registry</h4>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:152",
       "field": "start",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:150",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "meta.sensor_id:$sensors AND ( meta.src_location.data_source:scireg AND meta.dst_location.data_source:scireg ) AND (meta.src.community:$community OR meta.dst.community:$community)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Tasks with both ends tagged in Science Registry</h4>\n\n"
   }
  },
  {
   "title": "Total Number of Tasks Distributed Over Selected Time Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:114",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:112",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND (meta.src_organization:${confidential:raw} AND meta.dst_organization:${confidential:raw}) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Source Volume by Community",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:93",
       "fake": true,
       "field": "meta.src.community",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:87",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:88",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:89",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND meta.src_organization:${confidential:raw}",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Destination Volume by Community",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:93",
       "fake": true,
       "field": "meta.dst.community",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:87",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:88",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:89",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND meta.dst_organization:${confidential:raw}",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Source Countries",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:417",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "meta.src_country_name",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "meta.sensor_id:$sensors AND (meta.src_organization:${confidential:raw} AND meta.dst_organization:${confidential:raw}) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Destination Countries",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:417",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "meta.dst_country_name",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "meta.sensor_id:$sensors AND (meta.src_organization:${confidential:raw} AND meta.dst_organization:${confidential:raw}) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Sources not in Science Registry",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1316",
       "fake": true,
       "field": "meta.src_ip",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:417",
       "fake": true,
       "field": "meta.src_organization",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:234",
       "field": "meta.id",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND meta.src_organization:${confidential:raw}\nAND !meta.src.data_source:scireg",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destinations not in Science Registry",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1460",
       "fake": true,
       "field": "meta.dst_ip",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:242",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:234",
       "field": "meta.id",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND meta.dst_organization:${confidential:raw}\nAND !meta.dst.data_source:scireg",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 64 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: \n  <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a>\n  </img> \n  <img style=\"margin-left:30px\"\" src=\"https://netsage-project.github.io/Science-Registry/tacc.svg\" width=120 height=50> \n  <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://netsage-project.github.io/Science-Registry/EPOC-Data-Privacy.pdf\"> NetSage Data Policy </a> \n</div>"
   }
  }
 ]
}