{
 "title": "What is the Distribution of Globus Tasks by Resource?",
 "tags": [ "Globus task" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Organization",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_organization\", \"query\":\"meta.src_location.data_source:scireg\"}"
   },
   {
    "name": "resources",
    "label": "Resource",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_resource_name\", \"query\":\"meta.src_organization:$Organization\"}"
   },
   {
    "name": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   {
    "name": "country_scope",
    "label": "Scope",
    "query": "{\"find\":\"terms\", \"field\":\"meta.country_scope\"}"
   },
   { "name": "confidential", "label": "Display Confidential Tasks", "query": "Yes : *, No : (-UNAVAILABLE)" },
   { "name": "internal", "label": "Display Internal Transfers", "query": "Yes : *, No : !" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 0 },
   "options": {
    "content": " \n<center style=\"margin-top: 0px\">\n  </center>\n \n\n<blockquote style=\"margin-top: 0px; padding-right: 10%\">\n  <h1><b>Globus Tasks by Resource</b></h1>\n</font>\n\n  <li>  This dashboard shows top tasks from the selected organization and associated resources using the <a href=\"https://netsage.io/scienceregistry/\">NetSage Science Registry.</a>\n  <li> Select an organization from the list above, then select a resource. </li>\n <li>Globus Task endpoints are de-identified, and private data sources are marked \"Private\". </li>\n<li>Private Task data rates and totals are available via the toggle at the top of this dashboard. </li>\n  <li>All times are displayed in browser local time.</li>\n</blockquote>\n\n\n<br>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "<h1><center>Top Globus Tasks Sent by $Organization Resources</center></h1>"
   }
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:89",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:87",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.dst_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.src_resource_name:$resources",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:746",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:744",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.dst_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.src_resource_name:$resources",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:834",
       "fake": true,
       "field": "meta.dst_resource_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:828",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:829",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:830",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.src_resource_name:$resources AND meta.dst_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.src_location.data_source:scireg",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:468",
       "fake": true,
       "field": "meta.dst_resource_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:462",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:463",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:464",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.src_resource_name:$resources AND meta.dst_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.src_location.data_source:scireg",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Resource Distribution by Volume",
   "type": "esnet-chord-panel",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.src_resource_name",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "meta.dst_resource_name",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:260",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.src_resource_name:$resources AND meta.dst_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.src_location.data_source:scireg",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Resource Distribution by Rate",
   "type": "esnet-chord-panel",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.src_resource_name",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "meta.dst_resource_name",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "values.bits_per_second", "id": "1", "type": "avg" }
     ],
     "query": "meta.src_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.src_resource_name:$resources AND meta.dst_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.src_location.data_source:scireg",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 60 },
   "options": {
    "content": "<h1  style=\"margin-top:35px;\"><center>Top Globus Tasks Received by $Organization Resources</center></h1>"
   }
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.src_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.dst_resource_name:$resources",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:165",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:163",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.dst_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.src_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.dst_resource_name:$resources",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:834",
       "fake": true,
       "field": "meta.src_resource_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:828",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:829",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:830",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.src_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.dst_resource_name:$resources",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1022",
       "fake": true,
       "field": "meta.src_resource_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1016",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1017",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:1018",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.src_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.dst_resource_name:$resources",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Resource Distribution by Volume",
   "type": "esnet-chord-panel",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.src_resource_name",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "meta.dst_resource_name",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:260",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.dst_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.dst_resource_name:$resources AND meta.src_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.dst_location.data_source:scireg",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Resource Distribution by Rate",
   "type": "esnet-chord-panel",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "meta.src_resource_name",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "meta.dst_resource_name",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "values.bits_per_second", "id": "1", "type": "avg" }
     ],
     "query": "meta.dst_organization:$Organization AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND meta.sensor_id:$Sensors AND meta.dst_resource_name:$resources AND meta.src_organization:${confidential:raw} AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.dst_location.data_source:scireg",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 112 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Other Statistics about $Organization Globus Tasks</center></h1>"
   }
  },
  {
   "title": "Total Number of Tasks Distributed Over Selected Time Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1212",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1210",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_resource_name:$resources OR meta.dst_resource_name:$resources) AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND (meta.src_organization:${confidential:raw} AND meta.dst_organization:${confidential:raw}) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Resource Summary (As Source)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:794",
       "fake": true,
       "field": "meta.src_resource_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:786",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:787",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:788",
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:789",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_resource_name:$resources AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND (meta.src_organization:${confidential:raw} AND meta.dst_organization:${confidential:raw}) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Resource Summary (As Destination)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:794",
       "fake": true,
       "field": "meta.dst_resource_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:786",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:787",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:788",
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:789",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_resource_name:$resources AND (${internal:raw}(meta.src_organization:$Organization AND meta.dst_organization:$Organization)) AND (meta.src_organization:${confidential:raw} AND meta.dst_organization:${confidential:raw}) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 140 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: \n  <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a> \n  <img style=\"margin-left:10px\" src=\"/public/img/nsf.jpg\" width=50 height=50> \n    <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=2328479\"> 2328479 </a> \n  </img> \n  <img style=\"margin-left:30px\" src=\"/public/img/tacc.svg\" width=120 height=50> \n  <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://drive.google.com/file/d/19ljTq4xztalXyz5DhTfyjUMO1q4s0mYR/view\"> NetSage Data Policy </a> \n</div>"
   }
  }
 ]
}