{
 "title": "What are the Globus tasks by science discipline?",
 "tags": [ "Globus task" ],
 "time": { "from": "2025-05-29T15:30:24.269Z", "to": "2025-06-05T15:30:24.269Z" },
 "templating": {
  "list": [
   {
    "name": "org",
    "label": "Organization",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_organization\", \"size\": 10000000}"
   },
   {
    "name": "discipline",
    "label": "Discipline",
    "query": "{\"find\":\"terms\", \"field\":\"meta.scireg.src.discipline\", \"query\":\"meta.src_organization:$org OR meta.dst_organization:$org\"}"
   },
   {
    "name": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   {
    "name": "country_scope",
    "label": "Scope",
    "query": "{\"find\":\"terms\", \"field\":\"meta.country_scope\"}"
   },
   {
    "name": "community",
    "label": "Community",
    "query": "{\"find\":\"terms\",\"field\":\"meta.src.community\",\"query\":\"meta.src_organization:$org OR meta.dst_organization:$org\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 20, "x": 2, "y": 0 },
   "options": {
    "content": "\n\n<font color=\"#5794f2\">\n<blockquote style=\"margin-top: 0px\">\n  <h1><b>Globus Task Data by Science Discipline</b></h1>\n</font>\n\n  <li>This dashboard shows information related to science disciplines for top talkers using the <a href=\"https://netsage.io/scienceregistry/\">NetSage Science Registry</a>.</li>\n  <li>The Sankey graph shows the top ten source organizations by volume for the selected discipline(s) and organization(s) and their associated top three destination organizations, with thicker lines for larger task volumes.</li>\n   <li>All times are displayed in browser local time.</li>\n</blockquote>\n\n"
   }
  },
  {
   "title": "Task Volume for Selected Science Disciplines and Organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 1, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:39",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND (meta.scireg.src.discipline:$discipline OR meta.scireg.dst.discipline:$discipline) AND (meta.src_org_organization:$org OR meta.dst_organization:$org) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Task Volume for Selected Organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:88",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:86",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$Sensors && (meta.scireg.src.discipline:$discipline OR meta.scireg.dst.discipline:$discipline) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_organization:$org OR meta.dst_organization:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Task Volume for Selected Organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:115",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:113",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_organization:$org OR meta.dst_organization:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Number of Tasks for Selected Organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:146",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:144",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_organization:$org OR meta.dst_organization:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Task Volume by Source of Selected Disciplines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:91",
       "fake": true,
       "field": "meta.scireg.src.discipline",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:145",
       "fake": true,
       "field": "start",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:49",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": { "script": "_value/8" },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND (meta.src_organization:$org OR meta.dst_organization:$org) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.scireg.src.discipline:$discipline",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Task Volume by Destination of Selected Disciplines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:91",
       "fake": true,
       "field": "meta.scireg.dst.discipline",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:145",
       "fake": true,
       "field": "start",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:49",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": { "script": "_value/8" },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors && (meta.src_organization:$org OR meta.dst_organization:$org) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.scireg.dst.discipline:$discipline",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>Top Science Talkers</center></h3>\n"
   }
  },
  {
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:164",
       "fake": true,
       "field": "meta.src_organization",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": "Unknown",
        "order": "desc",
        "orderBy": "1",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:165",
       "fake": true,
       "field": "meta.scireg.src.discipline",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": "UNK-SRC",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:166",
       "field": "meta.dst_organization",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": "UNK-DST",
        "order": "desc",
        "orderBy": "1",
        "size": "3"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:162",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors && meta.scireg.src.discipline:$discipline && (meta.src_organization:$org OR meta.dst_organization:$org) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Pairs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:774",
       "fake": true,
       "field": "meta.src_organization",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:775",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:764",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:765",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:766",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:767",
       "field": "values.bits_per_second",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:768",
       "field": "values.bits_per_second",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND meta.scireg.src.discipline:$discipline AND (meta.src_organization:$org OR meta.dst_organization:$org) AND (meta.src.community:$community OR meta.dst.community:$community) AND (meta.src_organization:(-UNAVAILABLE) AND meta.dst_organization:(-UNAVAILABLE)) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 68 },
   "options": {
    "content": "<br/><br/>\n<center style=\"margin-top: 0px\"><h1><center>Summary of All Disciplines</center></h1>\n<center style=\"margin-top: 0px\"><center>Only tasks where source or destination has been tagged with a science discipline <br>\nfrom the Science Registry are counted.\n</center>"
   }
  },
  {
   "title": "Task Statistics by Source Discipline",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:242",
       "fake": true,
       "field": "meta.scireg.src.discipline",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:233",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:234",
       "field": "meta.id",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:235",
       "field": "values.bits_per_second",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:236",
       "field": "values.bits_per_second",
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_organization:$org OR meta.dst_organization:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Task Statistics by Destination Discipline",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:242",
       "fake": true,
       "field": "meta.scireg.dst.discipline",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:233",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:234",
       "field": "meta.id",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:235",
       "field": "values.bits_per_second",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:236",
       "field": "values.bits_per_second",
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_organization:$org OR meta.dst_organization:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 107 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: \n  <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a>\n  </img> \n  <img style=\"margin-left:30px\"\" src=\"https://netsage-project.github.io/Science-Registry/tacc.svg\" width=120 height=50> \n  <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://netsage-project.github.io/Science-Registry/EPOC-Data-Privacy.pdf\"> NetSage Data Policy </a> \n</div>"
   }
  }
 ]
}