{
 "title": "What are the top Globus tasks by country?",
 "tags": [ "Globus task" ],
 "time": { "from": "2025-05-29T15:30:24.269Z", "to": "2025-06-05T15:30:24.269Z" },
 "templating": {
  "list": [
   {
    "name": "Country",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_country_name\", \"size\": 5000}"
   },
   {
    "name": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   { "name": "confidential", "label": "Display Private Tasks", "query": "Yes : *, No : (-Private)" },
   {
    "name": "community",
    "label": "Community",
    "query": "{\"find\":\"terms\",\"field\":\"meta.src.community\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 0 },
   "options": {
    "content": "<div style=\"float:right;\">\n<a class=\"btn navbar-button gf-timepicker-nav-btn\" target=\"_blank\" href=\"/grafana/d/80IVUboZa/?var-src=$Country&from=${__from}&to=${__to}\" style=\"text-decoration: none; color: #52545C; font-weight: bold; background-color: white; padding: 0px; height: 32px; border: 1px solid #C7D0D9; display: flex; margin-top: 0px; padding-left: 5px; padding-right: 5px;\">See Individual Tasks for $Country</a>\n</div>\n<br clear=\"both\" />\n<font color=\"#5794f2\">\n<blockquote style=\"margin-top: 0px; font-size: 0.9em\">\n  <h1><b>Globus Tasks by Country</b></h1>\n</font>\n\n  <li>This dashboard shows top tasks with the specified country as the source or destination.</li>\n  <li>The first set of tables show top twenty data by both volume and rate and then the set of top pairs of organizations sharing data.</li>\n  <li>Other statistics about data to and from this country, including a Sankey graph for the top sources by volume, is then listed.</li>\n <li>Globus Task datasets have been de-identified. Globus Tasks where the organization is not disclosed are marked \"Private\". </li>\n<li>Private Task data rates and totals are available via the toggle at the top of this dashboard. </li>\n<li>All times are displayed in browser local time.</li>\n</blockquote>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "<h1><center>Top Destinations from $Country</center></h1>"
   }
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4162",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4160",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.dst_organization:${confidential:raw} AND meta.src.community:$community AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4238",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4236",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.dst_organization:${confidential:raw} AND meta.src.community:$community AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3972",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3966",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:3967",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:3968",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.dst_organization:${confidential:raw} AND meta.src.community:$community AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4339",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4333",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:4334",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:4335",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.dst_organization:${confidential:raw} AND meta.src.community:$community AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "<h1><center style=\"margin-top: 35px;\">Top Sources to $Country</center></h1>"
   }
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4752",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4750",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.src_organization:${confidential:raw} AND meta.dst.community:$community AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4828",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4826",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.src_organization:${confidential:raw} AND meta.dst.community:$community AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4562",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4556",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:4557",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:4558",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.src_organization:${confidential:raw} AND meta.dst.community:$community AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4913",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4907",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:4908",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:4909",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.src_organization:${confidential:raw} AND meta.dst.community:$community AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 66 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Top Endpoint Pairs in $Country</center></h1>"
   }
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1281",
       "fake": true,
       "field": "meta.src_organization",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1282",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1271",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:1272",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:1273",
       "field": "meta.id",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:1274",
       "field": "values.bits_per_second",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:1275",
       "field": "values.bits_per_second",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND ( meta.src_country_name:$Country OR meta.dst_country_name:$Country ) AND (meta.src_organization:${confidential:raw} AND meta.dst_organization:${confidential:raw}) AND (meta.src.community:$community OR meta.dst.community:$community)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 84 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>Sankey Graph of Globus Tasks in and out of $Country</center></h3>"
   }
  },
  {
   "title": "To $Country",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:996",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:997",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:994",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8e+9",
       "meta": {},
       "settings": { "script": "_value/8" },
       "type": "sum"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.src_organization:${confidential:raw} AND meta.dst.community:$community AND meta.sensor_id:$Sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "From $Country",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2457",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2458",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2455",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8e+9",
       "meta": {},
       "settings": { "script": "_value/8" },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.dst_organization:${confidential:raw} AND meta.src.community:$community AND meta.sensor_id:$Sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Number of Globus Tasks Distributed Over Selected Time Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:625",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:623",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_country_name:$Country OR meta.dst_country_name:$Country) AND ( meta.src_organization:${confidential:raw} AND (meta.src.community:$community OR meta.dst.community:$community) AND meta.dst_organization:${confidential:raw}) AND meta.sensor_id:$Sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 104 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: \n  <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a>\n  </img> \n  <img style=\"margin-left:30px\"\" src=\"https://netsage-project.github.io/Science-Registry/tacc.svg\" width=120 height=50> \n  <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://netsage-project.github.io/Science-Registry/EPOC-Data-Privacy.pdf\"> NetSage Data Policy </a> \n</div>"
   }
  }
 ]
}