{
 "title": "What do individual flows by country look like?",
 "tags": [ "Flow Data" ],
 "time": { "from": "2026-03-17T16:47:37.097Z", "to": "2026-03-24T16:47:37.097Z" },
 "templating": {
  "list": [
   {
    "name": "flow_type",
    "label": "Flow Type",
    "query": "{\"find\":\"terms\", \"field\":\"meta.flow_type\"}"
   },
   {
    "name": "src",
    "label": "Source Country",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_country_name\", \"query\": \"meta.flow_type:$flow_type\", \"size\": 100000} "
   },
   {
    "name": "dest",
    "label": "Destination Country",
    "query": "{\"find\":\"terms\", \"field\":\"meta.dst_country_name\", \"query\": \"meta.flow_type:$flow_type\", \"size\": 100000}"
   },
   {
    "name": "sensors",
    "label": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   {
    "name": "community",
    "label": "Community",
    "query": "{\"find\":\"terms\",\"field\":\"meta.src.community\"}"
   },
   { "name": "is_net_test", "label": "Show Test Traffic", "query": "yes,no" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font color=\"#5794f2\">\n<blockquote style=\"margin-top: 0px\">\n  <h1><b>Individual Flows per Country</b></h1>\n</font>\n\n  <li>This dashboard shows per-flow level data, given a particular source and destination country.</li>\n  <li>The table shows the volume, rate, duration (in hours, minutes and seconds) and retransmits for each flow.</li>\n  <li>Click on the timestamp of an individual flow to show more detailed information about that flow.</li>\n  <li>All times are displayed in browser local time.</li>\n</blockquote>\n\n"
   }
  },
  {
   "title": "# Flows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:70",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:68",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.src.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:183",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:181",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.src.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Avg Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:259",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:257",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.src.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Flows from Source to Destination",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:421",
       "fake": true,
       "field": "es_doc_id",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "12", "size": "1000" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:422",
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:423",
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:424",
       "fake": true,
       "field": "meta.src_organization",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:425",
       "fake": true,
       "field": "meta.src_ip",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:426",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:427",
       "fake": true,
       "field": "meta.dst_ip",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:409",
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:410",
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:412",
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.src.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1174",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1172",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.src.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:85",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:83",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.src.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>Summary Statistics</center></h3>"
   }
  },
  {
   "title": "Top Protocols",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:436",
       "fake": true,
       "field": "meta.protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:437",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:434",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.src.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:582",
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:583",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:580",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.src.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:636",
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:637",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:634",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.src.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 57 },
   "options": {
    "content": "<center style=\"margin-top:20px;\"><h1 style=\"margin-top:35px;\">Reverse Direction</h1></center>"
   }
  },
  {
   "title": "# Flows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:875",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:873",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.dst.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:992",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:990",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.dst.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Avg Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1068",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1066",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.dst.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Flows from Source to Destination (Reverse)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:421",
       "fake": true,
       "field": "es_doc_id",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "12", "size": "1000" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:422",
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:423",
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:424",
       "fake": true,
       "field": "meta.src_organization",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:425",
       "fake": true,
       "field": "meta.src_ip",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:426",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:427",
       "fake": true,
       "field": "meta.dst_ip",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:409",
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:410",
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:412",
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.dst.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume (Reverse)",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:209",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:207",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.dst.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate (Reverse)",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.dst.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 100 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center> Reverse Summary Statistics</center></h3>"
   }
  },
  {
   "title": "Top Protocols",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1029",
       "fake": true,
       "field": "meta.protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1030",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1027",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.dst.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1144",
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1145",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1142",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.dst.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1259",
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1260",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1257",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND meta.dst.community:$community AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>NetSage Sensors Observing Selected Country Flows</center></h3>"
   }
  },
  {
   "title": "Sensor Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:259",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:251",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:252",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:253",
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:254",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "((meta.src_country_name:$src AND meta.dst_country_name:$dest) OR (meta.src_country_name:$dest AND meta.dst_country_name:$src)) AND (meta.src.community:$community OR meta.dst.community:$community) AND meta.sensor_id:$sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 123 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: \n  <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a>\n  </img> \n  <img style=\"margin-left:30px\"\" src=\"https://netsage-project.github.io/Science-Registry/tacc.svg\" width=120 height=50> \n  <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://netsage-project.github.io/Science-Registry/EPOC-Data-Privacy.pdf\"> NetSage Data Policy </a> \n</div>"
   }
  }
 ]
}