{
 "title": "What are the top flows by organization?",
 "tags": [ "Flow Data" ],
 "time": { "from": "2025-05-29T15:30:24.269Z", "to": "2025-06-05T15:30:24.269Z" },
 "templating": {
  "list": [
   {
    "name": "Organization",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_organization\", \"size\": 10000000}"
   },
   {
    "name": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_resource_name\", \"query\":\"meta.src_organization:$Organization\"}"
   },
   {
    "name": "sortby",
    "label": "Show Resource",
    "query": "No : preferred_org , Yes : resource_name"
   },
   {
    "name": "community",
    "label": "Community",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src.community\", \"query\":\"meta.src_organization:$Organization OR meta.dst_organization:$Organization\"}"
   },
   {
    "name": "country_scope",
    "label": "Scope",
    "query": "{\"find\":\"terms\", \"field\":\"meta.country_scope\"}"
   },
   { "name": "is_net_test", "label": "Show Test Traffic", "query": "yes,no" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 0 },
   "options": {
    "content": "<div style=\"float:right;\">\n<a class=\"btn gf-timepicker-nav-btn\" target=\"_blank\" href=\"/grafana/d/-l3_u8nWk/individual-flows?var-src=$Organization&from=${__from}&to=${__to}\" style=\"text-decoration: none; color: #52545C; font-weight: bold; background-color: white; padding: 0px; height: 32px; border: 1px solid #C7D0D9; display: flex; margin-top: 0px; padding-left: 5px; padding-right: 5px;\">See Individual Flows for $Organization</a>\n<a class=\"btn gf-timepicker-nav-btn\" target=\"_blank\" href=\"/grafana/d/WNn1qyaiz/flows-by-science-discipline?var-org=$Organization&from=${__from}&to=${__to}\" style=\"text-decoration: none; color: #52545C; font-weight: bold; background-color: white; padding: 0px; height: 32px; border: 1px solid #C7D0D9; display: flex; margin-top: 0px; padding-left: 5px; padding-right: 5px;\">See Science Data for $Organization</a>\n</div>\n<br clear=\"both\">\n<font color=\"#5794f2\">\n<blockquote style=\"margin-top: 0px; padding-right: 10%\">\n  <h1><b>Flow Data by Organization</b></h1>\n</font>\n\n  <li>This dashboard shows top flows with the specified organization as the source or destination.</li>\n  <li>Select an organization from the list above, or start typing the name of the specific organization, the dropdown menu only shows 1000 results at a time.</li>\n  <li>Click on the name of an institution in one of the tables to go to the individual flows dashboard for that institution and the one selected for the page.</li>\n  <li><b>Please note that rate will be zero if only one sampled flow was detected.</b></li>\n  <li>All times are displayed in browser local time.</li>\n</blockquote>\n\n<br>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "<h1><center>Top Flows Sent by $Organization</center></h1>"
   }
  },
  {
   "title": "Number of Flows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:89",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:87",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_organization:$Organization AND meta.sensor_id:$Sensors AND meta.src_resource_name:$resource AND meta.dst.community:$community AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:165",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:163",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_organization:$Organization AND meta.sensor_id:$Sensors AND meta.src_resource_name:$resource AND meta.dst.community:$community AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:266",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      },
      {
       "field": "meta.dst_${sortby:raw}",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:260",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:261",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:262",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_organization:$Organization AND meta.sensor_id:$Sensors AND meta.src_resource_name:$resource AND meta.dst.community:$community AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:468",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      },
      {
       "field": "meta.dst_${sortby:raw}",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:462",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:463",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:464",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_organization:$Organization AND meta.sensor_id:$Sensors AND meta.src_resource_name:$resource AND meta.dst.community:$community AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "<h1  style=\"margin-top:35px;\"><center>Top Flows Received by $Organization</center></h1>"
   }
  },
  {
   "title": "Number of Flows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:657",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:655",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_organization:$Organization AND meta.sensor_id:$Sensors AND meta.dst_resource_name:$resource AND meta.src.community:$community AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:746",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:744",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.dst_organization:$Organization AND meta.sensor_id:$Sensors AND meta.dst_resource_name:$resource AND meta.src.community:$community AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:834",
       "fake": true,
       "field": "meta.src_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      },
      {
       "field": "meta.src_${sortby:raw}",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "5", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:828",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:829",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:830",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_organization:$Organization AND meta.sensor_id:$Sensors AND meta.dst_resource_name:$resource AND meta.src.community:$community AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1022",
       "fake": true,
       "field": "meta.src_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      },
      {
       "field": "meta.src_${sortby:raw}",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1016",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1017",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:1018",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_organization:$Organization AND meta.sensor_id:$Sensors AND meta.dst_resource_name:$resource AND meta.src.community:$community AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 67 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Other Statistics about $Organization Flows</center></h1>"
   }
  },
  {
   "title": "Total Number of Flows Distributed Over Selected Time Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1212",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1210",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_organization:$Organization OR meta.dst_organization:$Organization) AND meta.sensor_id:$Sensors AND (meta.src_resource_name:$resource OR meta.dst_resource_name:$resource) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Protocols",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:524",
       "fake": true,
       "field": "meta.protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:525",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:522",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_organization:$Organization OR meta.dst_organization:$Organization) AND meta.sensor_id:$Sensors AND (meta.src_resource_name:$resource OR meta.dst_resource_name:$resource) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:639",
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:640",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:637",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_organization:$Organization OR meta.dst_organization:$Organization) AND meta.sensor_id:$Sensors AND (meta.src_resource_name:$resource OR meta.dst_resource_name:$resource) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:754",
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:755",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:752",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_organization:$Organization OR meta.dst_organization:$Organization) AND meta.sensor_id:$Sensors AND (meta.src_resource_name:$resource OR meta.dst_resource_name:$resource) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 82 },
   "options": {
    "content": "<h3 style=\"margin-top:35px;\"><center>NetSage Sensors Observing $Organization Flows</center></h3>"
   }
  },
  {
   "title": "Sensor Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:794",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:786",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:787",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:788",
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:789",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_organization:$Organization OR meta.dst_organization:$Organization) AND meta.sensor_id:$Sensors AND (meta.src_resource_name:$resource OR meta.dst_resource_name:$resource) AND (meta.src.community:$community OR meta.dst.community:$community) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)  AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 96 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: \n  <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a>\n  </img> \n  <img style=\"margin-left:30px\"\" src=\"https://netsage-project.github.io/Science-Registry/tacc.svg\" width=120 height=50> \n  <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://netsage-project.github.io/Science-Registry/EPOC-Data-Privacy.pdf\"> NetSage Data Policy </a> \n</div>"
   }
  }
 ]
}