{
 "title": "What are the slowest SCP flows by organization?",
 "tags": [ "Flow Data" ],
 "time": { "from": "2026-04-09T15:35:59.109Z", "to": "2026-04-16T15:35:59.109Z" },
 "templating": {
  "list": [
   {
    "name": "src",
    "label": "Source Organization",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_organization\", \"query\": \"\", \"size\": 100000} "
   },
   {
    "name": "src_resource",
    "label": "Source Resource",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_resource_name\", \"query\":\"meta.src_organization:$src\"}"
   },
   {
    "name": "dest",
    "label": "Destination Organization",
    "query": "{\"find\":\"terms\", \"field\":\"meta.dst_organization\", \"query\": \"\", \"size\": 100000}"
   },
   { "name": "subnet", "label": "Subnet" },
   {
    "name": "sensors",
    "label": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   {
    "name": "country_scope",
    "label": "Scope",
    "query": "{\"find\":\"terms\", \"field\":\"meta.country_scope\", \"query\":\"meta.src_organization:$src AND meta.dst_organization:$dest\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 20, "x": 2, "y": 0 },
   "options": {
    "content": "\n<font color=\"#5794f2\">\n<blockquote style=\"margin-top: 0px\">\n  <h1><b>SSH Flows</b></h1>\n</font>\n\n  <li>This dashboard shows per-flow SSH related traffic on port 22 (SCP/RSYNC/SFTP), given a particular source and destination organization.</li>\n  <li>The table shows the volume, rate, duration (in hours, minutes and seconds)  for the 1000 slowest flows.</li>\n  <li>Click on the timestamp of an individual flow to show more detailed information about that flow.</li>\n  <li>All times are displayed in browser local time.</li>\n</blockquote>\n\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>\n"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Flows from Source to Destination",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:700",
       "fake": true,
       "field": "es_doc_id",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "30", "size": "1000" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:701",
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:702",
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:703",
       "fake": true,
       "field": "meta.src_organization",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:704",
       "fake": true,
       "field": "meta.src_ip",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:705",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:706",
       "fake": true,
       "field": "meta.dst_ip",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.dst_port",
       "id": "34",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "meta.src_port",
       "id": "35",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:688",
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:689",
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:691",
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization:$src AND meta.dst_organization:$dest AND meta.src_resource_name:$src_resource AND meta.sensor_id:$sensors AND (meta.src_port:22 OR meta.dst_port:22) AND (( (!(_exists_:meta.src_ip)) OR meta.src_ip:${subnet.regex}*) OR ( (!(_exists_:meta.dst_ip)) OR meta.dst_ip:${subnet.regex}*)) AND values.duration:[1800 TO *] AND values.num_bits:[8589934592 TO *]",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "options": {
    "content": "<center style=\"margin-top:35px;\"><h1>Reverse Direction</h1></center>"
   }
  },
  {
   "title": "Flows from Destination to Source (Reverse)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1115",
       "fake": true,
       "field": "es_doc_id",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "30", "size": "1000" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1116",
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1117",
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1118",
       "fake": true,
       "field": "meta.src_organization",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1119",
       "fake": true,
       "field": "meta.src_ip",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1120",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1121",
       "fake": true,
       "field": "meta.dst_ip",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.src_port",
       "id": "34",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "meta.dst_port",
       "id": "35",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1103",
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:1104",
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1106",
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization:$src AND meta.dst_organization:$dest AND meta.src_resource_name:$src_resource AND meta.sensor_id:$sensors AND (meta.src_port:22 OR meta.dst_port:22) AND (( (!(_exists_:meta.src_ip)) OR meta.src_ip:${subnet.regex}*) OR ( (!(_exists_:meta.dst_ip)) OR meta.dst_ip:${subnet.regex}*)) AND values.duration:[1800 TO *] and values.num_bits:[1000000000000 TO *] AND values.num_bits:[8589934592 TO *]",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>NetSage Sensors Observing Selected Organization Flows</center></h3>"
   }
  },
  {
   "title": "Sensor Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2263",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2255",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:2256",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:2257",
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:2258",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "((meta.src_organization:$src AND meta.dst_organization:$dest) OR (meta.src_organization:$dest AND meta.dst_organization:$src)) AND meta.sensor_id:$sensors AND (meta.src_resource_name:$src_resource OR meta.dst_resource_name:$src_resource) AND (meta.src_port:22 OR meta.dst_port:22) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (( (!(_exists_:meta.src_ip)) OR meta.src_ip:${subnet.regex}*) OR ( (!(_exists_:meta.dst_ip)) OR meta.dst_ip:${subnet.regex}*))",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 53 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: \n  <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a>\n  </img> \n  <img style=\"margin-left:30px\"\" src=\"https://netsage-project.github.io/Science-Registry/tacc.svg\" width=120 height=50> \n  <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://netsage-project.github.io/Science-Registry/EPOC-Data-Privacy.pdf\"> NetSage Data Policy </a> \n</div>"
   }
  }
 ]
}