{
 "title": "Bandwidth Dashboard",
 "tags": [ "netsage" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "links",
    "label": "Links",
    "query": "get link_name between(1451606400, $END) by link_name from interface where link_name != null and link_name not like \"ACE\" limit 100 offset 0 ordered by link_name asc"
   }
  ]
 },
 "panels": [
  {
   "type": "netsagenavigation",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 2, "y": 0 },
   "content": "<center><h1><b>Bandwidth Dashboard</b></h1></center>\n<center>The map above shows the min, max, and average bandwidth utilization of National Science Foundation’s International Research Network Connections Program links over the selected time period.</center>\n<center>The rows below show each of the links in more detail, including traffic volume, bandwidth distribution and total data transferred.</center>\n<center>A combined view of average bandwidth utilization is shown at the bottom of this page.</center>\n\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "select table",
     "target": "get max(aggregate(values.input, $quantify, max)) between ($START,$END) from interface where link_name != null",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "select table",
     "target": "get total_avg / 2 as values.avg from (get input_avg + output_avg as total_avg from (get average(aggregate(values.input, $quantify, average)) as input_avg, average(aggregate(values.output, $quantify, average)) as output_avg between ($START,$END) from interface where link_name != null))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "select table",
     "target": "get values.total / 8 as values.bytes from (get total * $TIMESPAN as values.total from (get input_sum + output_sum as total from (get average(aggregate(values.input,$quantify,average)) as input_sum, average(aggregate(values.output, $quantify, average)) as output_sum between ($START,$END) from interface where link_name != null)))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    }
   ]
  },
  {
   "type": "globalnoc-networkmap-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucket": [ "" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "input",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      },
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 60, average)": "input",
      "aggregate(values.output, 60, average)": "output"
     },
     "metricValueAliases": [
      "AZ",
      ""
     ],
     "metricValues_array": [
      "input",
      "Select Metric Value"
     ],
     "metric_array": [
      "link_name",
      "node"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, node, aggregate(values.input, 60, average),aggregate(values.output, 60, average) between (1570571291, 1570657691) by link_name from interface where (link_name like \".+\")",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": ".+" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "outerGroupOperator": [ "" ],
     "series": "select table",
     "target": "get node, intf, aggregate(values.input, $quantify, sum) as values.input, aggregate(values.output, $quantify, sum) as values.output by nothing from ( get node, intf, aggregate(values.input, $quantify, average)  as values.input,aggregate(values.output, $quantify, average)  as values.output between ($START, $END) by node, intf from interface where (node = \"8700.mren.org\" and intf in (\"10/2\",\"4/6\",\"6/6\",\"1/6\",\"5/3\",\"6/3\",\"2/5\",\"4/3\",\"2/3\",\"9/2\")) or (node = \"ex9208.sl.startap.net\" and intf in (\"xe-0/1/2\",\"ae2\",\"xe-0/3/2\",\"xe-0/2/2\",\"ge-5/0/2\",\"xe-0/1/0\")))",
     "target_alias": "Starlight $VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "outerGroupOperator": [ "" ],
     "series": "select table",
     "target": "get node, intf, aggregate(values.input, $quantify, sum) as values.input, aggregate(values.output, $quantify, sum) as values.output by nothing from ( get node, intf, aggregate(values.input, $quantify, average)  as values.input,aggregate(values.output, $quantify, average)  as values.output between ($START, $END) by node, intf from interface where (node =  \"mct01.miami.ampath.net\" and intf = \"ethernet6/2\") )",
     "target_alias": "AmLight $VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "outerGroupOperator": [ "" ],
     "series": "select table",
     "target": "get node, intf, aggregate(values.input, $quantify, sum) as values.input, aggregate(values.output, $quantify, sum) as values.output by nothing from ( get node, intf, aggregate(values.input, $quantify, average)  as values.input,aggregate(values.output, $quantify, average)  as values.output between ($START, $END) by node, intf from interface where (node = \"wrn-albu-sw-3.cenic.net\" and intf = \"ethernet5/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet6/15\") or (node = \"wrn-albu-sw-4.cenic.net\" and intf = \"ethernet3/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/3\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/10\") or (node = \"wrn-albu-sw-3.cenic.net\" and intf = \"ethernet7/1\") or (node = \"losa3-pw-sw-1.cenic.net\" and intf = \"ethernet4/1\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet7/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/2\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet1/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet4/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/8\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet7/7\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet3/1\") or (node = \"wrn-elpa-sw-1.cenic.net\" and intf = \"ethernet1/1\") or (node = \"losa3-pw-sw-1.cenic.net\" and intf = \"ethernet7/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet7/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/5\") or (node = \"wrn-elpa-sw-1.cenic.net\" and intf = \"ethernet5/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet1/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet16/5\") or (node = \"wrn-denv-sw-3.cenic.net\" and intf = \"ethernet7/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet6/20\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet13/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/5\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/6\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet7/1\") or (node = \"wrn-albu-sw-4.cenic.net\" and intf = \"ethernet5/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet3/2\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet1/1\") or (node = \"wrn-denv-sw-3.cenic.net\" and intf = \"ethernet1/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet1/1\") or (node = \"losa3-pw-sw-1.cenic.net\" and intf = \"ethernet7/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/7\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/9\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet16/7\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet6/2\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet3/2\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet5/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet4/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet5/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet9/1\") or (node = \"wrn-denv-sw-3.cenic.net\" and intf = \"ethernet5/2\") )",
     "target_alias": "CENIC $VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    }
   ]
  },
  { "title": "Link", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 23 } },
  { "title": "Traffic Volume", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 2, "y": 23 } },
  {
   "title": "(A to Z) Bandwidth Distribution",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 8, "y": 23 }
  },
  {
   "title": "(Z to A) Bandwidth Distribution",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 14, "y": 23 }
  },
  { "title": "Total Data", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 20, "y": 23 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "links" },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 25 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 25 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 33 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 33 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Chile 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Chile 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Chile 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Chile 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 33 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Chile 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Chile 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 41 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 41 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Sao Paulo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Sao Paulo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Sao Paulo 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Sao Paulo 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 41 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Sao Paulo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Miami to Sao Paulo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 49 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 49 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"NEAAR: New York to London 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"NEAAR: New York to London 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"NEAAR: New York to London 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"NEAAR: New York to London 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 49 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"NEAAR: New York to London 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"NEAAR: New York to London 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 57 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 57 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Los Angeles to Mauna Lani 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Los Angeles to Mauna Lani 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Los Angeles to Mauna Lani 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Los Angeles to Mauna Lani 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 57 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Los Angeles to Mauna Lani 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Los Angeles to Mauna Lani 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 65 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 65 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Mauna Lani to Sydney 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Mauna Lani to Sydney 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Mauna Lani to Sydney 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Mauna Lani to Sydney 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 65 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Mauna Lani to Sydney 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Mauna Lani to Sydney 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 73 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 73 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Guam 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Guam 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Guam 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Guam 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 73 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Guam 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Guam 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 81 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 81 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Los Angeles 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Los Angeles 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Los Angeles 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Los Angeles 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 81 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Los Angeles 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Los Angeles 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 89 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 89 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Sydney 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Sydney 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 89 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Sydney 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 89 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Sydney 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 89 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Sydney 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Oahu to Sydney 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 97 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 97 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Seattle to Oahu 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Seattle to Oahu 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 97 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Seattle to Oahu 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 97 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Seattle to Oahu 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 97 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Seattle to Oahu 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"PIREN: Seattle to Oahu 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 105 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 105 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Hong Kong to Guam 10GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Hong Kong to Guam 10GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Hong Kong to Guam 10GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Hong Kong to Guam 10GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 105 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Hong Kong to Guam 10GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Hong Kong to Guam 10GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 113 }, "content": "$links" },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 113 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Seattle to Tokyo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Seattle to Tokyo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 113 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "output"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Seattle to Tokyo 100GE\"))",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 113 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Seattle to Tokyo 100GE\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 113 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Seattle to Tokyo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 310, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"TransPAC: Seattle to Tokyo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "(A to Z) IRNC LINKS Average Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 60, average)": "A-Z"
     },
     "metricValueAliases": [ "A-Z" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "orderby_field": "link_name",
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 60, average) between (1570571291, 1570657691) by link_name from interface where (link_name like \".*\") ordered by link_name",
     "target_alias": "$VALUES $link_name",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": ".*" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "(Z to A) IRNC LINKS Average Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 60, average)": "Z-A"
     },
     "metricValueAliases": [ "Z-A" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "orderby_field": "link_name",
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 60, average) between (1570571291, 1570657691) by link_name from interface where (link_name like \".*\") ordered by link_name",
     "target_alias": "$VALUES $link_name",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": ".*" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "(A to Z) IRNC LINKS Maximum Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [ "max" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "max",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 60, max)": "Z-A"
     },
     "metricValueAliases": [ "A-Z" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "orderby_field": "link_name",
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 60, max) between (1570571291, 1570657691) by link_name from interface where (link_name like \".*\") ordered by link_name",
     "target_alias": "$VALUES $link_name",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": ".*" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "(Z to A) IRNC LINKS Maximum Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [ "max" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "max",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 60, max)": "A-Z"
     },
     "metricValueAliases": [ "Z-A" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "orderby_field": "link_name",
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 60, max) between (1570571291, 1570657691) by link_name from interface where (link_name like \".*\") ordered by link_name",
     "target_alias": "$VALUES $link_name",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": ".*" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 173 },
   "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a>netsage@iu.edu. </a> Thanks! <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:8px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
  }
 ]
}