{
 "title": "Flow Data per Country",
 "tags": [
  "flow",
  "netsage"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id.keyword\", \"query\":\"(meta.flow_type:sflow OR meta.flow_type:netflow)  AND NOT meta.sensor_id:cenic*\"}"
   },
   {
    "name": "Country",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_country_name.keyword\", \"query\":\"meta.sensor_id.keyword:$Sensors AND (-meta.src_country_name.keyword:\\\"\\\" AND -meta.src_country_name.keyword:\\\"==========================================================\\\")\", \"size\": 5000}"
   }
  ]
 },
 "panels": [
  {
   "type": "netsagenavigation",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 0 },
   "content": "<div style=\"float:right;\">\n<a class=\"btn navbar-button gf-timepicker-nav-btn\" target=\"_blank\" href=\"/grafana/d/80IVUboZk/individual-flows-per-country?var-src=$Country&from=${__from}&to=${__to}\" style=\"text-decoration: none; color: #52545C; font-weight: bold;\">See Individual Flows for $Country</a>\n</div>\n<br clear=\"both\" />\n<center><h1><b>Flow Data by Country</b></h1></center>\n<center>This dashboard shows the flow data for the selected country.</center>\n<center>The first set of tables show top ten data by both volume and rate and then the set of top pairs of organizations sharing data.</center>\n<center>Other statistics about data to and from this country, including a Sankey graph for the top sources by volume, is then listed.</center>\n<center>All times are displayed in browser local time.</center>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "content": "<h1><center>Top Destinations from $Country</center></h1>"
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.dst_country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      { "field": "select field", "id": "7", "type": "count" }
     ],
     "query": "meta.src_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.dst_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "decbytes", "label": "Total Volume" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.dst_country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.dst_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.dst_country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      { "field": "select field", "id": "7", "type": "count" }
     ],
     "query": "meta.src_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.dst_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.dst_country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.src_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.dst_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 },
   "content": "<h1><center style=\"margin-top: 35px;\">Top Sources to $Country</center></h1>"
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      { "field": "select field", "id": "7", "type": "count" }
     ],
     "query": "meta.dst_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.src_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 32 },
   "yaxes": [
    { "format": "decbytes", "label": "Total Volume" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.dst_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.src_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      { "field": "select field", "id": "7", "type": "count" }
     ],
     "query": "meta.dst_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.src_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 43 },
   "yaxes": [
    { "format": "bps", "label": "rate" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_country_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.dst_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.src_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
   "content": "<h1 style=\"margin-top:35px;\"><center>Top Flow Pairs with Endpoint(s) in $Country</center></h1>"
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_organization.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.dst_organization.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "field": "values.bits_per_second",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.bits_per_second",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id.keyword:$Sensors  AND ( meta.src_country_name.keyword:$Country OR meta.dst_country_name.keyword:$Country )",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 72 },
   "content": "<h1 style=\"margin-top:20px;\"><center>Other Flow Statistics related to $Country</center></h1>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 74 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(meta.src_country_name.keyword:$Country OR meta.dst_country_name.keyword:$Country) AND meta.sensor_id.keyword:$Sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 77 },
   "content": "<h3 style=\"margin-top:20px;\"><center>Sankey Graph of Top Flows in and out of $Country</center></h3>"
  },
  {
   "title": "to $Country",
   "type": "netsage-sankey",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_country_name.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.dst_country_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8e+9",
       "meta": {},
       "settings": { "script": { "inline": "_value/8e+9" } },
       "type": "sum"
      }
     ],
     "query": "meta.dst_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.src_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "from $Country",
   "type": "netsage-sankey",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_country_name.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.dst_country_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8e+9",
       "meta": {},
       "settings": { "script": { "inline": "_value/8e+9" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name.keyword:$Country AND meta.sensor_id.keyword:$Sensors AND -meta.dst_country_name.keyword:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Protocol",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.protocol.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(meta.src_country_name.keyword:$Country OR meta.dst_country_name.keyword:$Country) AND meta.sensor_id.keyword:$Sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(meta.src_country_name.keyword:$Country OR meta.dst_country_name.keyword:$Country) AND meta.sensor_id.keyword:$Sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(meta.src_country_name.keyword:$Country OR meta.dst_country_name.keyword:$Country) AND meta.sensor_id.keyword:$Sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 103 },
   "content": "<h3 style=\"margin-top:20px;\"><center>NetSage Sensors Observing $Country Flows</center></h3>"
  },
  {
   "title": "Links Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.sensor_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      { "field": "select field", "id": "7", "type": "count" }
     ],
     "query": "(meta.src_country_name.keyword:$Country OR meta.dst_country_name.keyword:$Country) AND meta.sensor_id.keyword:$Sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 113 },
   "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a>netsage@iu.edu. </a> Thanks!  <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:8px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
  }
 ]
}