{
 "title": "Flow Analysis",
 "tags": [
  "netsage",
  "flow"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensors",
    "label": "Flow Data",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id.keyword\", \"query\":\"(meta.flow_type:sflow OR meta.flow_type:netflow) AND NOT meta.sensor_id:cenic*\"}"
   },
   {
    "name": "links",
    "label": "SNMP Data",
    "query": "get link_name between($START, $END) by link_name from interface where link_name != null limit 100 offset 0"
   },
   {
    "name": "src_scope",
    "label": "Source Scope",
    "query": "meta.src_organization.keyword, meta.src_country_name.keyword, meta.src_continent.keyword, meta.src_asn, meta.src_port"
   },
   {
    "name": "dst_scope",
    "label": "Destination Scope",
    "query": "meta.dst_organization.keyword, meta.dst_country_name.keyword, meta.dst_continent.keyword, meta.dst_asn, meta.dst_port"
   },
   { "name": "filters", "label": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "netsagenavigation",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 0 },
   "content": "<div style=\"padding-right: 10%;\">\n<h1  style=\"margin-top:35px;\"><center><b>Flow Analysis</b></h1></center>\n<center>This dashboard shows SNMP data for the selected link on the SNMP graph below.</center>\n<center>It also shows flow pairs and top flows for the selected sensor, organized by the selected source and destination scopes.</center>\n<center>Select flow and SNMP data sources from the lists above, along with source and destination scopes.</center>\n<center>Clicking and dragging on the SNMP graph below will replace the current time range with a custom range based on the selected portion of the graph.</center>\n<center><b>Please note that the flow rate in the flow pairs table will be zero if only one sampled flow was detected.</b></center>\n<center>All times are displayed in browser local time.</center>\n</div>\n\n\n\n<br>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>\n\n\n\n"
  },
  {
   "title": "SNMP Graph of $links",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "content": "<h1  style=\"margin-top:35px;\"><center>Individual Flow Pairs</center></h1>"
  },
  {
   "title": "Flow Pairs",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.id.keyword",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "$src_scope",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.src_ip.keyword",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "$dst_scope",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.dst_ip.keyword",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "values.num_packets",
       "id": "25",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.tcp_rexmit_pkts",
       "id": "34",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.tcp_rtt_min",
       "id": "35",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$src_scope:\"\" AND -$dst_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "content": "<h1  style=\"margin-top:35px;\"><center>Top Sources of Flows</center></h1>",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "$src_scope",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "field": "values.num_bits",
       "id": "4",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      { "field": "select field", "id": "5", "type": "count" }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$src_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$src_scope",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$src_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "$src_scope",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "values.bits_per_second",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      { "field": "select field", "id": "4", "type": "count" }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$src_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$src_scope",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$src_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 58 },
   "content": "<h1  style=\"margin-top:35px;\"><center>Top Destinations of Flows</center></h1>",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "$dst_scope",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "field": "values.num_bits",
       "id": "4",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      { "field": "select field", "id": "5", "type": "count" }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$dst_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$dst_scope",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$dst_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "$dst_scope",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "values.bits_per_second",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      { "field": "select field", "id": "4", "type": "count" }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$dst_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "$dst_scope",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$dst_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 83 },
   "content": "<h1 style=\"margin-top:35px;\"><center>Other Flow Statistics</center></h1>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 86 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Protocols",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.protocol.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 89 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 89 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 98 },
   "content": "<h1 style=\"margin-top:35px;\"><center>Flow Data Summary For Selected Sensors</center></h1>"
  },
  {
   "title": "Links Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.sensor_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      { "field": "select field", "id": "7", "type": "count" }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 109 },
   "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu. </a> Thanks!  <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
  }
 ]
}