{
 "title": "Latency Patterns",
 "tags": [ "netsage" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "get source_description between($START, $END) by source_description from ps_owamp where source_description != null limit 100 offset 0"
   },
   {
    "name": "destination",
    "label": "Destination",
    "query": "get destination_description between($START, $END) by destination_description from ps_owamp where (source_description = \"$source\") limit 100 offset 0"
   },
   {
    "name": "measurement",
    "label": "Measurement",
    "query": "latency_avg, latency_min, latency_max"
   },
   { "name": "statistics", "label": "Statistics", "query": "average" }
  ]
 },
 "panels": [
  {
   "type": "netsagenavigation",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 20, "x": 2, "y": 0 },
   "content": "<center><h1><b>Latency Patterns</b></h1></center>\n<center>This is a heatmap for the Latency data across links over specific periods of time. </center>\n<center>The horizontal axis represents days and the vertical axis represents time of day. Darker squares show longer delays in data transmissions at those hours.</center>\n<center>The accompanying line graph shows the average, min, or max latency over time and the histogram shows the distribution of latency speeds.</center><center>All times are displayed in browser local time.</center>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>\n"
  },
  { "title": "$source -> $destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "destination" },
  {
   "title": "Latency Timeline",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$measurement" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1568069675, 1570661675) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms", "label": "Speed" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1568069675, 1570661675) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "target_alias": "$statistics",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1568069675, 1570661675) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  { "title": "$source -> $destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Latency Timeline",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$measurement" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1568069675, 1570661675) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"ESnet pS Server at Sacremento\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms", "label": "Speed" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1568069756, 1570661756) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"ESnet pS Server at Sacremento\"))",
     "target_alias": "$statistics",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1568069756, 1570661756) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"ESnet pS Server at Sacremento\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  { "title": "$source -> $destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Latency Timeline",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$measurement" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1568069757, 1570661757) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"ESnet pS Server at Seattle\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms", "label": "Speed" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1568069757, 1570661757) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"ESnet pS Server at Seattle\"))",
     "target_alias": "$statistics",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1568069757, 1570661757) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"ESnet pS Server at Seattle\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  { "title": "$source -> $destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Latency Timeline",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$measurement" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1558476418, 1561068418) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms", "label": "Speed" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "target_alias": "$statistics",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  { "title": "$source -> $destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Latency Timeline",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$measurement" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1558476418, 1561068418) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ms", "label": "Speed" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "target_alias": "$statistics",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  { "title": "$source -> $destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Latency Timeline",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$measurement" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1558476418, 1561068418) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "ms", "label": "Speed" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "target_alias": "$statistics",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  { "title": "$source -> $destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Latency Timeline",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$measurement" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1558476418, 1561068418) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "ms", "label": "Speed" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "target_alias": "$statistics",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  { "title": "$source -> $destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Latency Timeline",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$measurement" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1558476418, 1561068418) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "ms", "label": "Speed" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "target_alias": "$statistics",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "aggregate_all": false,
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "template",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "$measurement",
       "template": "$statistics",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "source_description, destination_description",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.latency_avg, 3600, average)": ""
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [
      "source_description",
      "destination_description",
      "source"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "series": "ps_owamp",
     "target": "get source_description, destination_description, source, aggregate(values.latency_avg, 3600, average) between (1559586098, 1562178098) by source_description, destination_description from ps_owamp where ((source_description = \"APAN pS Server at Tokyo\") and (destination_description = \"CENIC pS Server at Los Angeles\"))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "source_description", "op": "=", "right": "$source" },
       { "left": "destination_description", "op": "=", "right": "$destination" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 141 },
   "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a>netsage@iu.edu. </a> Thanks!  <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:8px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
  }
 ]
}