#!/bin/bash -e
#
# Close the current branch of the current repository.
#

WHEREAMI=$(dirname $0)
. "${WHEREAMI}/common"

[ "$1" ] && WHERE="$1" || WHERE="."

REPO_TOP=$(repo_top "${WHERE}")
cd "${REPO_TOP}"

CLOSE_FILE="${REPO_TOP}/BRANCH-CLOSED"
CLOSED=$(git branch -l | awk '$1 == "*" { print $2 }')

if [ -e "${CLOSE_FILE}" ]
then
    narrate "Branch ${CLOSED} already closed."
    exit 0
fi


${WHEREAMI}/create-next-versions "${REPO_TOP}"

git checkout "${CLOSED}"
touch "${CLOSE_FILE}"
git add "${CLOSE_FILE}"
git commit -m "Closing branch" "${CLOSE_FILE}"
git push

narrate "Branch ${CLOSED} closed."
