{
 "title": "Bandwidth Patterns",
 "tags": [ "netsage" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "links",
    "label": "Links",
    "query": "get link_name between($START, $END) by link_name from interface where link_name != null limit 100 offset 0"
   },
   {
    "name": "copy_of_links_old",
    "query": "TransPAC: Seattle to Tokyo 100GE, PIREN: Seattle to Oahu 100GE, PIREN: Oahu to Sydney 100GE, PIREN: Mauna Lani to Sydney 100GE, PIREN: Los Angeles to Mauna Lani 100GE, NEAAR: New York to London 100GE, AmLight: Miami to Sao Paulo 100GE, AmLight: Miami to Chile 100GE, AmLight: Chile to Sao Paolo 10GE"
   },
   { "name": "statistics", "label": "Statistics", "query": "average, min, max" },
   { "name": "data_direction", "label": "Data Direction", "query": "input, output" }
  ]
 },
 "panels": [
  {
   "type": "netsagenavigation",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 20, "x": 2, "y": 0 },
   "content": "<center><h1><b>Bandwidth Patterns</b></h1></center>\n<center>This dashboard shows heatmaps for the bandwidth data across exchange points and links as measured using SNMP. </center>\n<center>The horizontal axis represents days and the vertical axis represents time of day.</center>\n<center>Darker squares show higher data transmissions at those hours.</center>\n<center>All times are displayed in browser local time.</center>\n\n\n\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>\n"
  },
  { "title": "Exchange Points", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Amlight Exchange Point",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$data_direction" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get node, intf, aggregate(values.input, 3600, sum) as values.input, aggregate(values.output, 3600, sum) as values.output by nothing from ( get node, intf, aggregate(values.input, 3600, average)  as values.input,aggregate(values.output, 3600, average)  as values.output between ($START, $END) by node, intf from interface where (node =  \"mct01.miami.ampath.net\" or node = \"mct02.miami.ampath.net\") )",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "=", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pacific Wave Exchange Point",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$data_direction" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get node, intf, aggregate(values.input, 3600, sum) as values.input, aggregate(values.output, 3600, sum) as values.output by nothing from ( get node, intf, aggregate(values.input, 3600, average)  as values.input,aggregate(values.output, 3600, average)  as values.output between ($START, $END) by node, intf from interface where (node = \"wrn-albu-sw-3.cenic.net\" and intf = \"ethernet5/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet6/15\") or (node = \"wrn-albu-sw-4.cenic.net\" and intf = \"ethernet3/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/3\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/10\") or (node = \"wrn-albu-sw-3.cenic.net\" and intf = \"ethernet7/1\") or (node = \"losa3-pw-sw-1.cenic.net\" and intf = \"ethernet4/1\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet7/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/2\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet1/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet4/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/8\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet7/7\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet3/1\") or (node = \"wrn-elpa-sw-1.cenic.net\" and intf = \"ethernet1/1\") or (node = \"losa3-pw-sw-1.cenic.net\" and intf = \"ethernet7/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet7/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/5\") or (node = \"wrn-elpa-sw-1.cenic.net\" and intf = \"ethernet5/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet1/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet16/5\") or (node = \"wrn-denv-sw-3.cenic.net\" and intf = \"ethernet7/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet6/20\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet13/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/5\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/6\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet7/1\") or (node = \"wrn-albu-sw-4.cenic.net\" and intf = \"ethernet5/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet3/2\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet1/1\") or (node = \"wrn-denv-sw-3.cenic.net\" and intf = \"ethernet1/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet1/1\") or (node = \"losa3-pw-sw-1.cenic.net\" and intf = \"ethernet7/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/7\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/9\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet16/7\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet6/2\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet3/2\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet5/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet4/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet5/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet9/1\") or (node = \"wrn-denv-sw-3.cenic.net\" and intf = \"ethernet5/2\") )",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "=", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Starlight Exchange Point",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$data_direction" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get node, intf, aggregate(values.input, 3600, sum) as values.input, aggregate(values.output, 3600, sum) as values.output by nothing from ( get node, intf, aggregate(values.input, 3600, average)  as values.input,aggregate(values.output, 3600, average)  as values.output between ($START, $END) by node, intf from interface where (node = \"8700.mren.org\" and intf in (\"10/2\",\"4/6\",\"6/6\",\"1/6\",\"5/3\",\"6/3\",\"2/5\",\"4/3\",\"2/3\",\"9/2\")) or (node = \"ex9208.sl.startap.net\" and intf in (\"xe-0/1/2\",\"ae2\",\"xe-0/3/2\",\"xe-0/2/2\",\"ge-5/0/2\",\"xe-0/1/0\")))",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "=", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "title": "Selected Links", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$links ($data_direction)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "repeat": "links",
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [
       "",
       "and"
      ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "$data_direction" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get  link_name, aggregate(values.$data_direction, 3600, $statistics) between ($START,$END) from interface where  ( link_name = \"$links\" )",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "=", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 46 },
   "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu</a>.  Thanks!  <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
  }
 ]
}