{
 "title": "Bandwidth Dashboard",
 "tags": [ "netsage" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "links",
    "label": "Links",
    "query": "get link_name between($START, $END) by link_name from interface where link_name != null and link_name not like \"ACE\" limit 100 offset 0 ordered by link_name asc"
   }
  ]
 },
 "panels": [
  {
   "type": "netsage-nav-plugin",
   "gridPos": { "h": 1, "w": 1, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 20, "x": 2, "y": 0 },
   "options": {
    "content": "<center style=\"margin-top: 0px\"><h1><b>Bandwidth Dashboard</b></h1></center>\n<center style=\"margin-top: 0px\">The map shows the minimum, maximum, and average bandwidth utilization of the circuits and exchange points over the selected time period.</center>\n<center style=\"margin-top: 0px\">The rows below the map show each of the links in more detail, including traffic rate and total volume transferred.</center>\n<center style=\"margin-top: 0px\">A combined view of the average and maximum bandwidth utilization is shown at the bottom of the page.</center>\n<center style=\"margin-top: 0px\">All times are displayed in browser local time</center>\n\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>"
   }
  },
  {
   "title": "Single Link Max A-Z",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "select table",
     "target": "get max(aggregate(values.output, $quantify, max)) between ($START,$END) from interface where link_name != null",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Single Link Max Z-A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "select table",
     "target": "get max(aggregate(values.input, $quantify, max)) between ($START,$END) from interface where link_name != null",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Across All Links",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "select table",
     "target": "get input_avg + output_avg as values.total_avg from  ( get  average(aggregate(values.input, $quantify, average)) as input_avg,  average(aggregate(values.output, $quantify, average)) as output_avg between ($START,$END)  by nothing  from interface where link_name != null )",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Transferred",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": " ",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "select table",
     "target": "get total_bytes_sec  * 3600 as values.total_bytes from (         get input_bytes_sec_total + output_bytes_sec_total as total_bytes_sec from (        get aggregate(input_bytes_sec, 3600, sum) as input_bytes_sec_total, aggregate(output_bytes_sec, 3600, sum) as output_bytes_sec_total by nothing from (           get  aggregate(values.input, 3600, average) / 8 as input_bytes_sec,  aggregate(values.output, 3600, average) / 8 as output_bytes_sec between ($START,$END)  by link_name  from interface where link_name != null  )  ) )",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    }
   ]
  },
  {
   "type": "globalnoc-networkmap-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucket": [ "" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "input",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      },
      {
       "alias": "output",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 60, average)": "input",
      "aggregate(values.output, 60, average)": "output"
     },
     "metricValueAliases": [
      "AZ",
      ""
     ],
     "metricValues_array": [
      "input",
      "Select Metric Value"
     ],
     "metric_array": [
      "link_name",
      "node"
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, node, aggregate(values.input, 60, average),aggregate(values.output, 60, average) between (1570571291, 1570657691) by link_name from interface where (link_name like \".+\")",
     "target_alias": "$link_name $VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:453", "left": "link_name", "op": "like", "right": ".+" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "Select Metric" ],
     "outerGroupOperator": [ "" ],
     "series": "select table",
     "target": "get node, intf, aggregate(values.input, $quantify, sum) as values.input, aggregate(values.output, $quantify, sum) as values.output by nothing from ( get node, intf, aggregate(values.input, $quantify, average)  as values.input,aggregate(values.output, $quantify, average)  as values.output between ($START, $END) by node, intf from interface where (node = \"wrn-albu-sw-3.cenic.net\" and intf = \"ethernet5/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet6/15\") or (node = \"wrn-albu-sw-4.cenic.net\" and intf = \"ethernet3/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/3\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/10\") or (node = \"wrn-albu-sw-3.cenic.net\" and intf = \"ethernet7/1\") or (node = \"losa3-pw-sw-1.cenic.net\" and intf = \"ethernet4/1\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet7/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/2\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet1/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet4/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/8\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet7/7\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet3/1\") or (node = \"wrn-elpa-sw-1.cenic.net\" and intf = \"ethernet1/1\") or (node = \"losa3-pw-sw-1.cenic.net\" and intf = \"ethernet7/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet7/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/5\") or (node = \"wrn-elpa-sw-1.cenic.net\" and intf = \"ethernet5/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet1/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet16/5\") or (node = \"wrn-denv-sw-3.cenic.net\" and intf = \"ethernet7/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet6/20\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet13/1\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/5\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/6\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet7/1\") or (node = \"wrn-albu-sw-4.cenic.net\" and intf = \"ethernet5/1\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet3/2\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet1/1\") or (node = \"wrn-denv-sw-3.cenic.net\" and intf = \"ethernet1/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet1/1\") or (node = \"losa3-pw-sw-1.cenic.net\" and intf = \"ethernet7/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet15/7\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet8/9\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet16/7\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet6/2\") or (node = \"snvl2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet3/2\") or (node = \"wrn-denv-sw-4.cenic.net\" and intf = \"ethernet5/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet4/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet5/2\") or (node = \"losa2-pw-sw-1-mgmt-2.cenic.net\" and intf = \"ethernet9/1\") or (node = \"wrn-denv-sw-3.cenic.net\" and intf = \"ethernet5/2\") )",
     "target_alias": "CENIC $VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "Select Metric", "op": "", "right": "" }
      ]
     ]
    }
   ]
  },
  { "title": "Link", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 25 } },
  { "title": "Traffic Rate", "type": "text", "gridPos": { "h": 1, "w": 14, "x": 2, "y": 25 } },
  { "title": "Total Volume", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 25 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "links" },
  { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 27 }, "options": { "content": "**$links**" } },
  {
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 2, "y": 27 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "A-Z Avg",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:103", "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "Z-A Avg",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:133", "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "A-Z Max",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "max",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 210, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:103", "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "Z-A Max",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "max",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 210, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 210, average) between (1570571291, 1570657691) by link_name from interface where ((link_name like \"AmLight: Chile to Sao Paolo 100GE\"))",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:133", "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": [
      "average",
      "average"
     ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "* $TIMESPAN",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 310, average)": "A-Z"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "outerGroupOperator": [ "" ],
     "percentileValue": [
      "",
      ""
     ],
     "series": "interface",
     "target": "get link_name, values.output * 3600 from (get link_name, aggregate(values.output, 3600, average) / 8 as values.output between ($START, $END) by link_name from interface where ((link_name like \"$links\")))",
     "target_alias": "A-Z",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": true,
       "method": "average",
       "operation": "* $TIMESPAN",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 310, average)": "Z-A"
     },
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target": "get link_name, values.input * 3600 from (get link_name, aggregate(values.input, 3600, average) / 8 as values.input between ($START, $END) by link_name from interface where ((link_name like \"$links\")))",
     "target_alias": "Z-A",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 } },
  {
   "title": "(A to Z) Average Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 60, average)": "A-Z"
     },
     "metricValueAliases": [ "A-Z" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "orderby_field": "link_name",
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 60, average) between (1570571291, 1570657691) by link_name from interface where (link_name like \".*\") ordered by link_name",
     "target_alias": "$VALUES $link_name",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:284", "left": "link_name", "op": "like", "right": ".*" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 } },
  {
   "title": "(Z to A) Average Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [ "average" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 60, average)": "Z-A"
     },
     "metricValueAliases": [ "Z-A" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "orderby_field": "link_name",
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 60, average) between (1570571291, 1570657691) by link_name from interface where (link_name like \".*\") ordered by link_name",
     "target_alias": "$VALUES $link_name",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:326", "left": "link_name", "op": "like", "right": ".*" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "(A to Z) Maximum Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [ "max" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "Z-A",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "max",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.output, 60, max)": "Z-A"
     },
     "metricValueAliases": [ "A-Z" ],
     "metricValues_array": [ "output" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "orderby_field": "link_name",
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.output, 60, max) between (1570571291, 1570657691) by link_name from interface where (link_name like \".*\") ordered by link_name",
     "target_alias": "$VALUES $link_name",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:457", "left": "link_name", "op": "like", "right": ".*" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 215 } },
  {
   "title": "(Z to A) Maximum Utilization Over Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "bps", "label": "Rate" }
   ],
   "targets": [
    {
     "aggregator": [ "max" ],
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "A-Z",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "max",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliasMappings": {
      "aggregate(values.input, 60, max)": "A-Z"
     },
     "metricValueAliases": [ "Z-A" ],
     "metricValues_array": [ "input" ],
     "metric_array": [ "link_name" ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "orderby_field": "link_name",
     "outerGroupOperator": [ "" ],
     "percentileValue": [ "" ],
     "series": "interface",
     "target": "get link_name, aggregate(values.input, 60, max) between (1570571291, 1570657691) by link_name from interface where (link_name like \".*\") ordered by link_name",
     "target_alias": "$VALUES $link_name",
     "templateVariableValue": [ "" ],
     "timeField": "start",
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:521", "left": "link_name", "op": "like", "right": ".*" }
      ]
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 230 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 231 },
   "options": {
    "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu</a>.  Thanks! <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
   },
   "content": "<div class=\"netsage_footer\"> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu </a> Thanks! <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>\n"
  }
 ]
}