{
 "title": "Flow Analysis",
 "tags": [
  "netsage",
  "flow"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "links",
    "label": "SNMP Data",
    "query": "get link_name between($START, $END) by link_name from interface where link_name != null limit 100 offset 0"
   },
   {
    "name": "sensors",
    "label": "Flow Data",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id.keyword\", \"query\":\"(meta.flow_type:sflow OR meta.flow_type:netflow) AND NOT meta.sensor_id:cenic* AND NOT meta.sensor_id:*pacificwave*\"}"
   },
   {
    "name": "src_scope",
    "label": "Source Scope",
    "query": "meta.src_organization.keyword, meta.src_country_name.keyword, meta.src_continent.keyword, meta.src_asn, meta.src_port"
   },
   {
    "name": "dst_scope",
    "label": "Destination Scope",
    "query": "meta.dst_organization.keyword, meta.dst_country_name.keyword, meta.dst_continent.keyword, meta.dst_asn, meta.dst_port"
   },
   { "name": "filters", "label": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "netsagenavigation",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 0 },
   "options": {
    "content": "<div style=\"padding-right: 10%;\">\n<h1  style=\"margin-top:35px;\"><center><b>Flow Analysis</b></h1></center>\n<center>This dashboard shows SNMP data for the selected link on the SNMP graph below.</center>\n<center>It also shows flow pairs and top flows for the selected sensor, organized by the selected source and destination scopes as well as the volume above (in bits) and rate under (in bits per second).</center>\n<center>Select flow and SNMP data sources from the lists above, along with source and destination scopes as well as the volume above (in bits) and rate under (in bits per second).</center>\n<center>Clicking and dragging on the SNMP graph below will replace the current time range with a custom range based on the selected portion of the graph.</center>\n<center><strong>Please note that the flow rate in the flow pairs table will be zero if only one sampled flow was detected.</strong></center>\n<center>All times are displayed in browser local time.</center></div>\n\n\n\n<br>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>\n\n\n\n"
   },
   "content": "<div style=\"padding-right: 10%;\">\n<h1  style=\"margin-top:35px;\"><center><b>Flow Analysis</b></h1></center>\n<center>This dashboard shows SNMP data for the selected link on the SNMP graph below.</center>\n<center>It also shows flow pairs and top flows for the selected sensor, organized by the selected source and destination scopes as well as the volume above (in bits) and rate under (in bits per second).</center>\n<center>Select flow and SNMP data sources from the lists above, along with source and destination scopes as well as the volume above (in bits) and rate under (in bits per second).</center>\n<center>Clicking and dragging on the SNMP graph below will replace the current time range with a custom range based on the selected portion of the graph.</center>\n<center><strong>Please note that the flow rate in the flow pairs table will be zero if only one sampled flow was detected.</strong></center>\n<center>All times are displayed in browser local time.</center></div>\n\n\n\n<br>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>\n\n\n\n"
  },
  {
   "title": "SNMP Graph of $links",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "input",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:485", "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    },
    {
     "combineAllBy": "nothing",
     "displayFormat": "series",
     "func": [
      {
       "alias": "",
       "align": "",
       "bucket": "",
       "expanded": false,
       "method": "average",
       "operation": "",
       "percentile": "85",
       "root": true,
       "target": "output",
       "template": "",
       "title": "Aggregate",
       "type": "Aggregate",
       "wrapper": []
      }
     ],
     "groupby_field": "link_name",
     "inlineGroupOperator": [
      [ "" ]
     ],
     "metricValueAliases": [ "" ],
     "metricValues_array": [ "Select Metric Value" ],
     "metric_array": [ "link_name" ],
     "outerGroupOperator": [ "" ],
     "series": "interface",
     "target_alias": "$VALUE",
     "templateVariableValue": [ "" ],
     "type": "timeserie",
     "whereClauseGroup": [
      [
       { "$$hashKey": "object:520", "left": "link_name", "op": "like", "right": "$links" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<h1  style=\"margin-top:35px;\"><center>Top Flow Pairs</center></h1>"
   },
   "content": "<h1  style=\"margin-top:35px;\"><center>Top Flow Pairs</center></h1>"
  },
  {
   "title": "Flow Pairs",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:394",
       "fake": true,
       "field": "$src_scope",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:395",
       "fake": true,
       "field": "$dst_scope",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:384",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:385",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:386",
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:387",
       "field": "values.bits_per_second",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:388",
       "field": "values.bits_per_second",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$src_scope:\"\" AND -$dst_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "<h1  style=\"margin-top:35px;\"><center>Top Sources of Flows</center></h1>"
   },
   "content": "<h1  style=\"margin-top:35px;\"><center>Top Sources of Flows</center></h1>",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:616",
       "field": "$src_scope",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:610",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:611",
       "field": "values.num_bits",
       "id": "4",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:612",
       "field": "meta.id.keyword",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$src_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:753",
       "field": "$src_scope",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:747",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:748",
       "field": "values.bits_per_second",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:749",
       "field": "meta.id.keyword",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$src_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "<h1  style=\"margin-top:35px;\"><center>Top Destinations of Flows</center></h1>"
   },
   "content": "<h1  style=\"margin-top:35px;\"><center>Top Destinations of Flows</center></h1>",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:887",
       "field": "$dst_scope",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:881",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:882",
       "field": "values.num_bits",
       "id": "4",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:883",
       "field": "meta.id.keyword",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$dst_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1016",
       "field": "$dst_scope",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1010",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1011",
       "field": "values.bits_per_second",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:1012",
       "field": "meta.id.keyword",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$dst_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 88 },
   "options": {
    "content": "<h1  style=\"margin-top:35px;\"><center>Individual Flows</center></h1>"
   },
   "content": "<h1  style=\"margin-top:35px;\"><center>Individual Flows</center></h1>"
  },
  {
   "title": "Flow Pairs",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1188",
       "fake": true,
       "field": "meta.id.keyword",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1189",
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1190",
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1191",
       "fake": true,
       "field": "$src_scope",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1192",
       "fake": true,
       "field": "meta.src_ip.keyword",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1193",
       "fake": true,
       "field": "$dst_scope",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1194",
       "fake": true,
       "field": "meta.dst_ip.keyword",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1176",
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:1177",
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1178",
       "field": "values.num_packets",
       "id": "25",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:1179",
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:1180",
       "field": "values.tcp_rexmit_pkts",
       "id": "34",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:1181",
       "field": "values.tcp_rtt_min",
       "id": "35",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors AND -$src_scope:\"\" AND -$dst_scope:\"\"",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 106 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Other Flow Statistics</center></h1>"
   },
   "content": "<h1 style=\"margin-top:35px;\"><center>Other Flow Statistics</center></h1>"
  },
  {
   "title": "Total Large Flows Observed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1520",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1518",
       "field": "meta.id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Protocols",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:65",
       "fake": true,
       "field": "meta.protocol.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:66",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:63",
       "field": "meta.id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:146",
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:147",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:144",
       "field": "meta.id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:451",
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:452",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:449",
       "field": "meta.id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 121 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Flow Data Summary For Selected Sensors</center></h1>"
   },
   "content": "<h1 style=\"margin-top:35px;\"><center>Flow Data Summary For Selected Sensors</center></h1>"
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1597",
       "fake": true,
       "field": "meta.sensor_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1589",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:1590",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:1591",
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1592",
       "field": "meta.id.keyword",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id.keyword:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 132 },
   "options": {
    "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu</a>.  Thanks!  <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
   },
   "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu</a>.  Thanks!  <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
  }
 ]
}