{
 "title": "Flow Data per Country",
 "tags": [
  "flow",
  "netsage"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Country",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_country_name\", \"size\": 5000}"
   },
   {
    "name": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   { "name": "is_net_test", "label": "Show Test Traffic", "query": "yes,no" }
  ]
 },
 "panels": [
  { "type": "netsage-nav-plugin", "gridPos": { "h": 1, "w": 1, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 0 },
   "options": {
    "content": "<div style=\"float:right;\">\n<a class=\"btn navbar-button gf-timepicker-nav-btn\" target=\"_blank\" href=\"/grafana/d/80IVUboZk/individual-flows-per-country?var-src=$Country&from=${__from}&to=${__to}\" style=\"text-decoration: none; color: #52545C; font-weight: bold; background-color: white; padding: 0px; height: 32px; border: 1px solid #C7D0D9; display: flex; margin-top: 0px; padding-left: 5px; padding-right: 5px;\">See Individual Flows for $Country</a>\n</div>\n<br clear=\"both\" />\n<div style=\"font-size: 0.9em\" >\n<center style=\"margin-top: 0px\"><h1><b>Flow Data by Country</b></h1></center>\n<center style=\"margin-top: 0px\">This dashboard shows top flows with the specified country as the source or destination.</center>\n<center style=\"margin-top: 0px\">The first set of tables show top twenty data by both volume and rate and then the set of top pairs of organizations sharing data.</center>\n<center style=\"margin-top: 0px\">Other statistics about data to and from this country, including a Sankey graph for the top sources by volume, is then listed.</center>\n<center style=\"margin-top: 0px\"><b>Please note that rate will be zero if only one sampled flow was detected.</b></center>\n<center style=\"margin-top: 0px\">All times are displayed in browser local time.</center>\n</div>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<h1><center>Top Destinations from $Country</center></h1>"
   }
  },
  {
   "title": "# Flows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4162",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "meta.id", "id": "1", "type": "cardinality" }
     ],
     "query": "meta.src_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4238",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4236",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3972",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      },
      {
       "field": "meta.id",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3966",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "$$hashKey": "object:3968",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3972",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3966",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "$$hashKey": "object:3968",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4339",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4333",
       "field": "values.bits_per_second",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:4334",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:4335",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<h1><center style=\"margin-top: 35px;\">Top Sources to $Country</center></h1>"
   }
  },
  {
   "title": "# Flows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4752",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "meta.id", "id": "1", "type": "cardinality" }
     ],
     "query": "meta.dst_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4828",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4826",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4562",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      },
      {
       "field": "meta.id",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4556",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "$$hashKey": "object:4558",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4562",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4556",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "$$hashKey": "object:4558",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4913",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4907",
       "field": "values.bits_per_second",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:4908",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:4909",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 65 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Top Flow Pairs with Endpoint(s) in $Country</center></h1>"
   }
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1281",
       "fake": true,
       "field": "meta.src_organization",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1282",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1271",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:1272",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:1273",
       "field": "meta.id",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:1274",
       "field": "values.bits_per_second",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:1275",
       "field": "values.bits_per_second",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id:$Sensors  AND ( meta.src_country_name:$Country OR meta.dst_country_name:$Country ) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 83 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Other Flow Statistics related to $Country</center></h1>"
   }
  },
  {
   "title": "# Flows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:625",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "meta.id", "id": "1", "type": "cardinality" }
     ],
     "query": "(meta.src_country_name:$Country OR meta.dst_country_name:$Country) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 89 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>Sankey Graph of Top Flows in and out of $Country</center></h3>"
   }
  },
  {
   "title": "To $Country",
   "type": "netsage-sankey",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:996",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:997",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:994",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.dst_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.src_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "From $Country",
   "type": "netsage-sankey",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2457",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2458",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2455",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8e+9",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$Country AND meta.sensor_id:$Sensors AND -meta.dst_country_name:\"\" AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Protocols",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2501",
       "fake": true,
       "field": "meta.protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2502",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2499",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_country_name:$Country OR meta.dst_country_name:$Country) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 106 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2616",
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2617",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2614",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_country_name:$Country OR meta.dst_country_name:$Country) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 106 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:2731",
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:2732",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:2729",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_country_name:$Country OR meta.dst_country_name:$Country) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 115 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>NetSage Sensors Observing $Country Flows</center></h3>"
   }
  },
  {
   "title": "Sensor Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:794",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.id",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:786",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "$$hashKey": "object:789",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_country_name:$Country OR meta.dst_country_name:$Country) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:794",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:786",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "$$hashKey": "object:789",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_country_name:$Country OR meta.dst_country_name:$Country) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    },
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:794",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "meta.id",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "values.bits_per_second", "id": "1", "type": "avg" },
      {
       "$$hashKey": "object:789",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "(meta.src_country_name:$Country OR meta.dst_country_name:$Country) AND meta.sensor_id:$Sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 128 },
   "options": {
    "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu</a>.  Thanks!  <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
   }
  }
 ]
}