{
 "title": "Globus Tasks",
 "tags": [
  "flow",
  "netsage"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   {
    "name": "country_scope",
    "label": "Scope",
    "query": "{\"find\":\"terms\", \"field\":\"meta.country_scope\"}"
   },
   { "name": "is_internal_transfer", "label": "Show Internal Transfers", "query": "no,yes" }
  ]
 },
 "panels": [
  {
   "type": "netsage-nav-plugin",
   "gridPos": { "h": 1, "w": 1, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 18, "x": 3, "y": 0 },
   "options": {
    "content": "<center style=\"margin-top: 0px\"><font color=\"#5794f2\"><h1><b>Globus Tasks</b></h1></font></center>\n<center style=\"margin-top: 0px\">This dashboard shows the top sources and destinations by volume and rate of all Globus Tasks.</center>\n<center style=\"margin-top: 0px\">Click on an organization name in one of the tables to see the Task data dashboard for that organization.</center>\n<center style=\"margin-top: 0px\">The slope graph below shows the top pairs of organizations by volume.  Darker lines correspond with larger volume.</center>\n<center style=\"margin-top: 0px\">All times are displayed in browser local time.</center>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<h1><center>Top Sources</center></h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:93",
       "fake": true,
       "field": "meta.src_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:87",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:88",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:89",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND -meta.src_organization:\"\" AND -meta.dst_organization:\"\" AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.internal_transfer)) OR meta.internal_transfer:no OR meta.internal_transfer:$is_internal_transfer)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:261",
       "fake": true,
       "field": "meta.src_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:255",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:256",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:257",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND -meta.src_organization:\"\" AND -meta.dst_organization:\"\" AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.internal_transfer)) OR meta.internal_transfer:no OR meta.is_internal_transfer:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Top Destinations</center></h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "By Volume",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:470",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:464",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:465",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:466",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND -meta.src_organization:\"\" AND -meta.dst_organization:\"\" AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:623",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "25" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:617",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:618",
       "field": "values.bits_per_second",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:619",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND -meta.src_organization:\"\" AND -meta.dst_organization:\"\" AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 58 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Top Pairs</center></h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Pairs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:774",
       "fake": true,
       "field": "meta.src_organization",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:775",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:764",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:765",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:766",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:767",
       "field": "values.bits_per_second",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:768",
       "field": "values.bits_per_second",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND -meta.src_organization:\"\" AND -meta.dst_organization:\"\" AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top 30 Pairs by Data Volume",
   "type": "netsage-slopegraph-panel",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:365",
       "fake": true,
       "field": "meta.src_organization",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:366",
       "field": "meta.dst_organization",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:363",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND -meta.src_organization:\"\" AND -meta.dst_organization:\"\" AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 93 },
   "options": {
    "content": "<h1 style=\"margin-top:35px;\"><center>Other Globus Tasks Statistics Related To Selected Sensor(s)</center></h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Number of Tasks Distributed Over Selected Time Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:625",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:623",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 99 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a> <img style=\"margin-left:10px\" src=\"/public/img/nsf.jpg\" width=50 height=50> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=2328479\"> 2328479 </a> </img> <img style=\"margin-left:30px\" src=\"/public/img/tacc.svg\" width=120 height=50> <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://drive.google.com/file/d/19ljTq4xztalXyz5DhTfyjUMO1q4s0mYR/view\"> NetSage Data Policy </a> </div>"
   },
   "content": "<div class=\"netsage_footer\"> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu </a> Thanks! <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>\n",
   "targets": [
    {}
   ]
  }
 ]
}