{
 "title": "Tasks by Science Discipline",
 "tags": [
  "flow",
  "netsage"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org",
    "label": "Organization",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_preferred_org\", \"size\": 10000000}"
   },
   {
    "name": "discipline",
    "label": "Discipline",
    "query": "{\"find\":\"terms\", \"field\":\"meta.scireg.src.discipline\", \"query\":\"-meta.scireg.src.discipline:\\\"Network Monitoring\\\" AND (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org)\"}"
   },
   {
    "name": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   {
    "name": "country_scope",
    "label": "Scope",
    "query": "{\"find\":\"terms\", \"field\":\"meta.country_scope\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "netsage-nav-plugin",
   "gridPos": { "h": 1, "w": 1, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 20, "x": 2, "y": 0 },
   "options": {
    "content": "\n<center style=\"margin-top: 0px\"><font color=\"#5794f2\"><h1><b>Globus Task Data by Science Discipline</b></h1></font></center>\n<center style=\"margin-top: 0px\">This dashboard shows information related to science disciplines for top talkers using the <a href=\"https://scienceregistry.netsage.global\">NetSage Science Registry</a>.</center>\n<center style=\"margin-top: 0px\">The map shows only the top 100 pairs of organizations with at least one end tagged in the science registry.  Larger dots indicate larger tasks.</center>\n<center style=\"margin-top: 0px\">The Sankey graph shows the top ten source organizations by volume for the selected discipline(s) and organization(s)<br/> and their associated top three destination organizations, with thicker lines for larger task volumes.</center>\n<center style=\"margin-top: 0px\"><b>Note that in the Summary tables, if only one sampled task was detected, the rate will be zero.</b></center>\n<center style=\"margin-top: 0px\">All times are displayed in browser local time.</center>\n\n\n <!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Volume for Selected Science Disciplines and Organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 1, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:39",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors && (meta.scireg.src.discipline:$discipline OR meta.scireg.dst.discipline:$discipline) AND (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org)AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Task Volume for Selected Organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:88",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:86",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$Sensors && (meta.scireg.src.discipline:$discipline OR meta.scireg.dst.discipline:$discipline) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Task Volume for Selected Organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:115",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:113",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Number of Tasks for Selected Organizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:146",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:144",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Task Volume by Source of Selected Disciplines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:91",
       "fake": true,
       "field": "meta.scireg.src.discipline",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:145",
       "fake": true,
       "field": "start",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:49",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors && (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org)AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.scireg.src.discipline:$discipline",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Task Volume by Destination of Selected Disciplines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:91",
       "fake": true,
       "field": "meta.scireg.dst.discipline",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:145",
       "fake": true,
       "field": "start",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:49",
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors && (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org)AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND meta.scireg.dst.discipline:$discipline",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Flows between Top 100 by Volume",
   "type": "netsage-migrationmap",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:189",
       "fake": true,
       "field": "meta.scireg.src.discipline",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:190",
       "fake": true,
       "field": "meta.scireg.dst.discipline",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": "N/A",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:191",
       "fake": true,
       "field": "meta.src_preferred_org",
       "id": "5",
       "settings": {
        "min_doc_count": 1,
        "missing": "N/A",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:192",
       "fake": true,
       "field": "meta.scireg.src.resource",
       "id": "6",
       "settings": {
        "min_doc_count": 1,
        "missing": "N/A",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:193",
       "fake": true,
       "field": "meta.src_preferred_location.lat",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:194",
       "fake": true,
       "field": "meta.src_preferred_location.lon",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:195",
       "fake": true,
       "field": "meta.dst_preferred_org",
       "id": "10",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:196",
       "fake": true,
       "field": "meta.scireg.dst.resource",
       "id": "11",
       "settings": {
        "min_doc_count": 1,
        "missing": "N/A",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:162",
       "fake": true,
       "field": "meta.dst_preferred_location.lat",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:197",
       "fake": true,
       "field": "meta.dst_preferred_location.lon",
       "id": "9",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:187",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors && meta.scireg.src.discipline:$discipline && (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>Top Science Talkers</center></h3>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:164",
       "fake": true,
       "field": "meta.src_preferred_org",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": "Unknown",
        "order": "desc",
        "orderBy": "1",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:165",
       "fake": true,
       "field": "meta.scireg.src.discipline",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": "UNK-SRC",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:166",
       "field": "meta.dst_preferred_org",
       "id": "2",
       "settings": {
        "min_doc_count": 1,
        "missing": "UNK-DST",
        "order": "desc",
        "orderBy": "1",
        "size": "3"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:162",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.sensor_id:$Sensors && meta.scireg.src.discipline:$discipline && (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Pairs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:774",
       "fake": true,
       "field": "meta.src_preferred_org",
       "id": "8",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:775",
       "fake": true,
       "field": "meta.dst_preferred_org",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:764",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:765",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:766",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:767",
       "field": "values.bits_per_second",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:768",
       "field": "values.bits_per_second",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id:$Sensors && meta.scireg.src.discipline:$discipline && (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 90 },
   "options": {
    "content": "<br/><br/>\n<center style=\"margin-top: 0px\"><h1><center>Summary of All Disciplines</center></h1>\n<center style=\"margin-top: 0px\"><center>Only tasks where source or destination has been tagged with a science discipline <br>\nfrom the Science Registry are counted.\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Statistics by Source Discipline",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:242",
       "fake": true,
       "field": "meta.scireg.src.discipline",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:233",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:234",
       "field": "meta.id",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:235",
       "field": "values.bits_per_second",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:236",
       "field": "values.bits_per_second",
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Task Statistics by Destination Discipline",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:242",
       "fake": true,
       "field": "meta.scireg.dst.discipline",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:233",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:234",
       "field": "meta.id",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "count"
      },
      {
       "$$hashKey": "object:235",
       "field": "values.bits_per_second",
       "id": "10",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:236",
       "field": "values.bits_per_second",
       "id": "11",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "meta.sensor_id:$Sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND (meta.src_preferred_org:$org OR meta.dst_preferred_org:$org)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 129 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a> <img style=\"margin-left:10px\" src=\"/public/img/nsf.jpg\" width=50 height=50> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=2328479\"> 2328479 </a> </img> <img style=\"margin-left:30px\" src=\"/public/img/tacc.svg\" width=120 height=50> <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://drive.google.com/file/d/19ljTq4xztalXyz5DhTfyjUMO1q4s0mYR/view\"> NetSage Data Policy </a> </div>"
   },
   "content": "<div class=\"netsage_footer\"> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu </a> Thanks! <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>\n",
   "targets": [
    {}
   ]
  }
 ]
}