{
 "title": "What do individual flows by country look like?",
 "tags": [ "netsage" ],
 "time": { "from": "2022-03-21T17:21:52.058Z", "to": "2022-03-28T17:21:52.059Z" },
 "templating": {
  "list": [
   {
    "name": "flow_type",
    "label": "Flow Type",
    "query": "{\"find\":\"terms\", \"field\":\"meta.flow_type\"}"
   },
   {
    "name": "src",
    "label": "Source Country",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_country_name\", \"query\": \"meta.flow_type:$flow_type\", \"size\": 100000} "
   },
   {
    "name": "dest",
    "label": "Destination Country",
    "query": "{\"find\":\"terms\", \"field\":\"meta.dst_country_name\", \"query\": \"meta.flow_type:$flow_type\", \"size\": 100000}"
   },
   {
    "name": "sensors",
    "label": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   { "name": "is_net_test", "label": "Show Test Traffic", "query": "yes,no" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>\n<h1><center style=\"margin-top: 0px\"><b>Individual Flows per Country</b></center></h1>\n<center style=\"margin-top: 0px\">This dashboard shows per-flow level data, given a particular source and destination country.</center>\n<center style=\"margin-top: 0px\">The table shows the volume, rate, duration (in hours, minutes and seconds) and retransmits for each flow. </center>\n<center style=\"margin-top: 0px\">Click on the timestamp of an individual flow to show more detailed information about that flow.</center>\n<center style=\"margin-top: 0px\"><b>Please note that the retransmit information is only available for archive flow data;<br>\nand rate and duration will be zero for flows where only one sample was detected.</b></center>\n<center style=\"margin-top: 0px\">All times are displayed in browser local time.</center>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "# Flows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:70",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:68",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:183",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:181",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Avg Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:259",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:257",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Flows from Source to Destination",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:421",
       "fake": true,
       "field": "es_doc_id",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "12", "size": "1000" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:422",
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:423",
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:424",
       "fake": true,
       "field": "meta.src_organization",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:425",
       "fake": true,
       "field": "meta.src_ip",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:426",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:427",
       "fake": true,
       "field": "meta.dst_ip",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:409",
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:410",
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:412",
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:413",
       "field": "values.tcp_rexmit_pkts",
       "id": "34",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1174",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1172",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:85",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:83",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Retransmits",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:107",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:105",
       "field": "values.tcp_rexmit_pkts",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 58 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>Summary Statistics</center></h3>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Protocols",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:436",
       "fake": true,
       "field": "meta.protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:437",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:434",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:582",
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:583",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:580",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:636",
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:637",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:634",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$src AND meta.dst_country_name:$dest  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 68 },
   "options": {
    "content": "<center style=\"margin-top:20px;\"><h1 style=\"margin-top:35px;\">Reverse Direction</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "# Flows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:875",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:873",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:992",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:990",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Avg Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1068",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1066",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Flows from Source to Destination (Reverse)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:421",
       "fake": true,
       "field": "es_doc_id",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "12", "size": "1000" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:422",
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:423",
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:424",
       "fake": true,
       "field": "meta.src_organization",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:425",
       "fake": true,
       "field": "meta.src_ip",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:426",
       "fake": true,
       "field": "meta.dst_organization",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:427",
       "fake": true,
       "field": "meta.dst_ip",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:409",
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:410",
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:412",
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "$$hashKey": "object:413",
       "field": "values.tcp_rexmit_pkts",
       "id": "34",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume (Reverse)",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:209",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:207",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate (Reverse)",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Retransmits (Reverse)",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:317",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:315",
       "field": "values.tcp_rexmit_pkts",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 122 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center> Reverse Summary Statistics</center></h3>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Protocols",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1029",
       "fake": true,
       "field": "meta.protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1030",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1027",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1144",
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1145",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1142",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1259",
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1260",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1257",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_country_name:$dest AND meta.dst_country_name:$src  AND meta.sensor_id:$sensors AND meta.flow_type:$flow_type AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 132 },
   "options": {
    "content": "<h3 style=\"margin-top:16px;\"><center>NetSage Sensors Observing Selected Country Flows</center></h3>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sensor Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:259",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:251",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:252",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:253",
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:254",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "((meta.src_country_name:$src AND meta.dst_country_name:$dest) OR (meta.src_country_name:$dest AND meta.dst_country_name:$src)) AND meta.sensor_id:$sensors AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 146 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a> <img style=\"margin-left:10px\" src=\"/public/img/nsf.jpg\" width=50 height=50> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=2328479\"> 2328479 </a> </img> <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://drive.google.com/file/d/19ljTq4xztalXyz5DhTfyjUMO1q4s0mYR/view\"> NetSage Data Policy </a> </div>"
   },
   "content": "<div class=\"netsage_footer\"> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu </a> Thanks! <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>\n",
   "targets": [
    {}
   ]
  }
 ]
}