{
 "title": "What are the current flow data summary statistics?",
 "tags": [
  "flow",
  "netsage"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensors",
    "label": "Sensors",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id\"}"
   },
   {
    "name": "country_scope",
    "label": "Scope",
    "query": "{\"find\":\"terms\", \"field\":\"meta.country_scope\"}"
   },
   { "name": "is_net_test", "label": "Show Test Traffic", "query": "yes,no" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 2, "y": 0 },
   "options": {
    "content": "<center style=\"margin-top: 0px\"><font color=\"#5794f2\"><h1><b>Other Flow Statistics</b></h1></font></center>\n<center style=\"margin-top: 0px\">This dashboard provides a summary of flow information for science registry tagging, organizations, countries, protocols, ports, as well as volume and counts of flows. </center>\n<center style=\"margin-top: 0px\">All times are displayed in browser local time. </center>\n<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Flow Sensor Health (last 3d)",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:247",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "$$hashKey": "object:128",
       "field": "start",
       "id": "2",
       "settings": { "interval": "3d", "min_doc_count": "0", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:126", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:106",
       "field": "start",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:104",
       "field": "meta.src_organization",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:168",
       "field": "meta.src_country_name",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:1381",
       "field": "meta.src_asn",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:1392",
       "field": "meta.dst_asn",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:1403",
       "field": "meta.dst_organization",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      },
      {
       "$$hashKey": "object:1414",
       "field": "meta.dst_country_name",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 6 },
   "options": {
    "content": "<br>\n<h4  style = 'margin-top: 0px; font-weight:bold; color:#FF780A'>Source Organizations</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "options": {
    "content": "<br>\n<h4  style = 'margin-top: 0px; font-weight:bold; color:#FF780A'>Destination Organizations</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 8 },
   "options": {
    "content": "<br>\n<h4  style = 'margin-top: 0px; font-weight:bold; color:#FF780A'>Source ASNs</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 8 },
   "options": {
    "content": "<br>\n<h4  style = 'margin-top: 0px; font-weight:bold; color:#FF780A'>Destination ASNs</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 10 },
   "options": {
    "content": "<br>\n<h4  style = 'margin-top: 0px; font-weight:bold; color:#FF780A'>Source Countries</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 10 },
   "options": {
    "content": "<br>\n<h4  style = 'margin-top: 0px; font-weight:bold; color:#FF780A'>Destination Countries</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:106",
       "field": "start",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test) AND meta.ip_version:4",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 12 },
   "options": {
    "content": "<br>\n<h4  style = 'margin-top: 0px; font-weight:bold; color:#FF780A'>IPv4 Flows</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:106",
       "field": "start",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test) AND meta.ip_version:6",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 12 },
   "options": {
    "content": "<br>\n<h4  style = 'margin-top: 0px; font-weight:bold; color:#FF780A'>IPv6 Flows</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1051",
       "field": "start",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1049",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "meta.sensor_id:$sensors AND ( _exists_:meta.scireg.src.org_name  OR _exists_:meta.scireg.dst.org_name  ) AND NOT ( _exists_:meta.scireg.src.org_name  AND _exists_:meta.scireg.dst.org_name  ) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 14 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Flows with only one end tagged in Science Registry</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:152",
       "field": "start",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:150",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "meta.sensor_id:$sensors AND ( _exists_:meta.scireg.src.org_name  AND _exists_:meta.scireg.dst.org_name  ) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 14 },
   "options": {
    "content": "<h4  style = 'margin-top: 16px; font-weight:bold; color:#FF780A'>Flows with both ends tagged in Science Registry</h4>\n\n"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:41",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:39", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Total Number of Flows Distributed Over Selected Time Period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:114",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:112",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Protocols",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:49",
       "fake": true,
       "field": "meta.protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:50",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:47",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:284",
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:285",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:282",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "-meta.src_port:0 AND meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:405",
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:406",
       "field": "start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:403",
       "field": "meta.id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "-meta.dst_port:0 AND meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Source Countries",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:417",
       "fake": true,
       "field": "meta.src_country_name",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "meta.src_country_name",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "meta.sensor_id:$sensors AND (!(_exists_:meta.scireg.src.discipline)) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Destination Countries",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:417",
       "fake": true,
       "field": "meta.dst_country_name",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "meta.dst_country_name",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "meta.sensor_id:$sensors AND (!(_exists_:meta.scireg.src.discipline)) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Count of Flows by Sensor (Stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1039",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1040",
       "field": "start",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1037", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Sensor Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:794",
       "fake": true,
       "field": "meta.sensor_id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:786",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:787",
       "field": "values.num_bits",
       "id": "5",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:788",
       "field": "values.bits_per_second",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:789",
       "field": "meta.id",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Sources not in Science Registry",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1316",
       "fake": true,
       "field": "meta.src_ip",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:417",
       "fake": true,
       "field": "meta.src_preferred_org",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:234",
       "field": "meta.id",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND (!(_exists_:meta.scireg.src.discipline)) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destinations not in Science Registry",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1460",
       "fake": true,
       "field": "meta.dst_ip",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:242",
       "fake": true,
       "field": "meta.dst_preferred_org",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:232",
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      },
      {
       "$$hashKey": "object:234",
       "field": "meta.id",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.sensor_id:$sensors AND (!(_exists_:meta.scireg.dst.discipline)) AND ((!(_exists_:meta.country_scope)) OR meta.country_scope:$country_scope) AND ((!(_exists_:meta.is_network_testing)) OR meta.is_network_testing:no OR meta.is_network_testing:$is_net_test)",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "<div>Questions, concerns, or other issues: <a href=\"mailto:epoc@tacc.utexas.edu\">epoc@tacc.utexas.edu</a> <img style=\"margin-left:10px\" src=\"/public/img/nsf.jpg\" width=50 height=50> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=2328479\"> 2328479 </a> </img> <span style=\"float:right; position:relative; top:15px\"> <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://drive.google.com/file/d/19ljTq4xztalXyz5DhTfyjUMO1q4s0mYR/view\"> NetSage Data Policy </a> </div>"
   },
   "content": "<div class=\"netsage_footer\"> If you have any questions, concerns, or other issues, feel free to contact us at <a href=\"mailto:netsage@iu.edu\">netsage@iu.edu </a> Thanks! <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:15px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>\n",
   "targets": [
    {}
   ]
  }
 ]
}